// Copyright (c) Six Labors.
// Licensed under the Six Labors Split License.

using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Net;
using System.Text;
using System.Text.RegularExpressions;

namespace UnicodeTrieGenerator;

/// <content>
/// Contains the generator for the OpenType language system tag map.
/// </content>
public static partial class Generator
{
    private const string AdvancedTypographicRelativePath = @"src\SixLabors.Fonts\Tables\AdvancedTypographic";

    [GeneratedRegex(@"<tr>\s*<td[^>]*>(?<name>.*?)</td>\s*<td[^>]*>(?<tag>.*?)</td>\s*<td[^>]*>(?<iso>.*?)</td>\s*</tr>", RegexOptions.Singleline)]
    private static partial Regex LanguageTagRowRegex();

    [GeneratedRegex("<[^>]+>")]
    private static partial Regex HtmlTagRegex();

    [GeneratedRegex("[A-Z0-9]{2,4}")]
    private static partial Regex LanguageSystemTagRegex();

    [GeneratedRegex("^[a-z]{2,3}(?![a-z])")]
    private static partial Regex IsoCodeRegex();

    /// <summary>
    /// Generates the ISO 639 to OpenType language system tag map from the checked-in
    /// registry snapshots.
    /// </summary>
    /// <remarks>
    /// Inputs, both stored under <c>Rules</c>:
    /// <list type="bullet">
    /// <item><description><c>languagetags.html</c>: the OpenType language system tag registry.
    /// <see href="https://learn.microsoft.com/en-us/typography/opentype/spec/languagetags"/></description></item>
    /// <item><description><c>language-subtag-registry.txt</c>: the IANA BCP 47 subtag registry, used to
    /// key macrolanguages' sublanguages and retired codes' replacements.
    /// <see href="https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry"/></description></item>
    /// </list>
    /// </remarks>
    public static void GenerateOpenTypeLanguageTagMap()
    {
        List<LanguageTagEntry> entries = ParseOpenTypeLanguageTagRegistry();

        // Key the registry rows by each ISO 639 code they list. Rows are alphabetical by
        // language system name; within one code deprecated tags order after current ones.
        Dictionary<string, List<LanguageTagEntry>> map = new(StringComparer.Ordinal);
        foreach (LanguageTagEntry entry in entries)
        {
            foreach (string code in entry.IsoCodes)
            {
                if (!map.TryGetValue(code, out List<LanguageTagEntry>? list))
                {
                    list = [];
                    map[code] = list;
                }

                if (list.Any(x => x.Tag == entry.Tag))
                {
                    continue;
                }

                int insertAt = entry.Deprecated ? list.Count : list.FindIndex(x => x.Deprecated);
                list.Insert(insertAt < 0 ? list.Count : insertAt, entry);
            }
        }

        AddIanaAliases(map);

        StringBuilder sb = new();
        sb.AppendLine("// Copyright (c) Six Labors.");
        sb.AppendLine("// Licensed under the Six Labors Split License.");
        sb.AppendLine();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("namespace SixLabors.Fonts.Tables.AdvancedTypographic;");
        sb.AppendLine();
        sb.AppendLine("/// <content>");
        sb.AppendLine("/// Contains the generated ISO 639 code to OpenType language system tag data.");
        sb.AppendLine("/// </content>");
        sb.AppendLine("internal sealed partial class OpenTypeLanguageTagMap");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Creates the map from lowercase ISO 639 codes to the OpenType language system");
        sb.AppendLine("    /// tags registered for that language, in registry order with deprecated tags last.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <returns>The populated map.</returns>");
        sb.AppendLine("    private static Dictionary<string, Tag[]> CreateIsoLanguageMap()");
        sb.AppendLine("        => new(StringComparer.Ordinal)");
        sb.AppendLine("        {");

        foreach (KeyValuePair<string, List<LanguageTagEntry>> pair in map.OrderBy(x => x.Key, StringComparer.Ordinal))
        {
            string tags = string.Join(", ", pair.Value.Select(x => $"Tag.Parse(\"{x.Tag}\")"));
            string names = string.Join("; ", pair.Value.Select(x => x.Name).Distinct());
            sb.AppendLine(CultureInfo.InvariantCulture, $"            {{ \"{pair.Key}\", new[] {{ {tags} }} }}, // {names}");
        }

        sb.AppendLine("        };");
        sb.AppendLine("}");

        string path = GetFullPath(Path.Combine(AdvancedTypographicRelativePath, "OpenTypeLanguageTagMap.Generated.cs"));
        File.WriteAllText(path, sb.ToString());
    }

    /// <summary>
    /// Parses the OpenType language system tag registry rows.
    /// </summary>
    /// <returns>The parsed entries in registry order.</returns>
    private static List<LanguageTagEntry> ParseOpenTypeLanguageTagRegistry()
    {
        using StreamReader reader = GetStreamReader("languagetags.html");
        string html = reader.ReadToEnd();

        List<LanguageTagEntry> entries = [];
        foreach (Match row in LanguageTagRowRegex().Matches(html))
        {
            string name = DecodeCell(row.Groups["name"].Value);
            string tagCell = DecodeCell(row.Groups["tag"].Value);
            string isoCell = DecodeCell(row.Groups["iso"].Value);

            Match tagMatch = LanguageSystemTagRegex().Match(tagCell);
            if (!tagMatch.Success)
            {
                continue;
            }

            // Rows that define no ISO codes (for example the phonetic transcription tags
            // keyed by BCP 47 variant subtags) are handled by the hand-written resolver.
            List<string> codes = [];
            if (!isoCell.StartsWith("Cf.", StringComparison.Ordinal))
            {
                foreach (string part in isoCell.Split(','))
                {
                    Match code = IsoCodeRegex().Match(part.Trim());
                    if (code.Success && !codes.Contains(code.Value))
                    {
                        codes.Add(code.Value);
                    }
                }
            }

            if (codes.Count == 0)
            {
                continue;
            }

            entries.Add(new LanguageTagEntry(
                name,
                tagMatch.Value.PadRight(4),
                codes,
                tagCell.Contains("deprecated", StringComparison.OrdinalIgnoreCase)));
        }

        return entries;
    }

    /// <summary>
    /// Adds map keys for macrolanguages' sublanguages and retired codes' replacements
    /// from the IANA BCP 47 subtag registry, so lookups by those codes resolve to the
    /// tags of the language the registry points them at.
    /// </summary>
    /// <param name="map">The map keyed by ISO 639 code.</param>
    private static void AddIanaAliases(Dictionary<string, List<LanguageTagEntry>> map)
    {
        using StreamReader reader = GetStreamReader("language-subtag-registry.txt");
        string registry = reader.ReadToEnd();

        List<(string Subtag, string Target)> aliases = [];
        foreach (string record in registry.Split("%%"))
        {
            string? subtag = null;
            string? macrolanguage = null;
            string? preferred = null;
            bool isLanguage = false;

            foreach (string line in record.Split('\n'))
            {
                string trimmed = line.Trim();
                if (trimmed.StartsWith("Type:", StringComparison.Ordinal))
                {
                    isLanguage = trimmed[5..].Trim() == "language";
                }
                else if (trimmed.StartsWith("Subtag:", StringComparison.Ordinal))
                {
                    subtag = trimmed[7..].Trim();
                }
                else if (trimmed.StartsWith("Macrolanguage:", StringComparison.Ordinal))
                {
                    macrolanguage = trimmed[14..].Trim();
                }
                else if (trimmed.StartsWith("Preferred-Value:", StringComparison.Ordinal))
                {
                    preferred = trimmed[16..].Trim();
                }
            }

            if (!isLanguage || subtag is null || subtag.Contains("..", StringComparison.Ordinal))
            {
                continue;
            }

            // The Chinese macrolanguage is deliberately not expanded: its sublanguages
            // carry their own registry rows where mappings exist, and the script and
            // region sensitive zh resolution lives in the hand-written resolver.
            if (macrolanguage is not null and not "zh")
            {
                aliases.Add((subtag, macrolanguage));
            }

            if (preferred is not null && !preferred.Contains('-', StringComparison.Ordinal))
            {
                aliases.Add((subtag, preferred));
            }
        }

        foreach ((string subtag, string target) in aliases.OrderBy(x => x.Subtag, StringComparer.Ordinal))
        {
            if (map.ContainsKey(subtag))
            {
                continue;
            }

            if (TryResolveEntries(map, target, out List<LanguageTagEntry>? entries))
            {
                map[subtag] = entries;
            }
        }
    }

    /// <summary>
    /// Resolves the map entries for an ISO 639 code, bridging between the two and three
    /// letter forms via <see cref="CultureInfo"/> when the direct key is absent.
    /// </summary>
    /// <param name="map">The map keyed by ISO 639 code.</param>
    /// <param name="code">The code to resolve.</param>
    /// <param name="entries">The resolved entries.</param>
    /// <returns><see langword="true"/> if the code resolved; otherwise <see langword="false"/>.</returns>
    private static bool TryResolveEntries(
        Dictionary<string, List<LanguageTagEntry>> map,
        string code,
        [NotNullWhen(true)] out List<LanguageTagEntry>? entries)
    {
        if (map.TryGetValue(code, out entries))
        {
            return true;
        }

        try
        {
            CultureInfo culture = new(code);
            return map.TryGetValue(culture.ThreeLetterISOLanguageName.ToLowerInvariant(), out entries)
                || map.TryGetValue(culture.TwoLetterISOLanguageName.ToLowerInvariant(), out entries);
        }
        catch (CultureNotFoundException)
        {
            entries = null;
            return false;
        }
    }

    private static string DecodeCell(string value)
        => WebUtility.HtmlDecode(HtmlTagRegex().Replace(value, string.Empty)).Trim();

    /// <summary>
    /// A parsed OpenType language system tag registry row.
    /// </summary>
    private sealed class LanguageTagEntry
    {
        public LanguageTagEntry(string name, string tag, List<string> isoCodes, bool deprecated)
        {
            this.Name = name;
            this.Tag = tag;
            this.IsoCodes = isoCodes;
            this.Deprecated = deprecated;
        }

        public string Name { get; }

        public string Tag { get; }

        public List<string> IsoCodes { get; }

        public bool Deprecated { get; }
    }
}
