// Copyright (c) Six Labors.
// Licensed under the Apache License, Version 2.0.

// <auto-generated />
using System;
using System.Collections.Generic;

namespace SixLabors.Fonts.Unicode.Resources
{
    internal static partial class MyanmarShapingData
    {
        public static int[][] StateTable => new int[32][]
        {
            new int[] { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 },
            new int[] { 0,2,2,3,4,5,5,0,6,7,2,2,0,0,0,8,0,0,9,0,10,11,12,13,0 },
            new int[] { 0,0,0,14,15,16,16,0,17,18,0,0,0,0,0,0,0,0,0,0,19,20,21,22,0 },
            new int[] { 0,0,0,0,0,23,23,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,0 },
            new int[] { 0,24,24,0,0,0,0,0,0,0,0,0,0,0,0,24,0,0,0,0,0,0,0,0,0 },
            new int[] { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 },
            new int[] { 0,0,0,0,0,23,23,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 },
            new int[] { 0,0,0,3,0,23,23,0,6,7,0,0,0,0,0,0,0,0,0,0,0,0,0,13,0 },
            new int[] { 0,0,0,14,15,16,16,0,17,18,0,0,0,0,0,0,0,0,0,0,19,20,21,22,0 },
            new int[] { 0,2,2,0,0,0,0,0,0,0,2,2,0,0,0,2,0,0,0,0,0,0,0,0,0 },
            new int[] { 0,0,0,3,0,23,23,0,6,7,0,0,0,0,0,0,0,0,0,0,10,11,0,13,0 },
            new int[] { 0,0,0,3,0,23,23,0,6,7,0,0,0,0,0,0,0,0,0,0,0,11,0,13,0 },
            new int[] { 0,0,0,3,0,23,23,0,6,7,0,0,0,0,0,0,0,0,0,0,10,11,12,13,0 },
            new int[] { 0,0,0,25,0,23,23,0,6,26,0,0,0,0,0,0,0,0,0,0,27,0,0,13,0 },
            new int[] { 0,0,0,0,0,16,16,0,17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22,0 },
            new int[] { 0,28,28,0,0,0,0,0,0,0,0,0,0,0,0,28,0,0,0,0,0,0,0,0,0 },
            new int[] { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 },
            new int[] { 0,0,0,0,0,16,16,0,17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 },
            new int[] { 0,0,0,14,0,16,16,0,17,18,0,0,0,0,0,0,0,0,0,0,0,0,0,22,0 },
            new int[] { 0,0,0,14,0,16,16,0,17,18,0,0,0,0,0,0,0,0,0,0,19,20,0,22,0 },
            new int[] { 0,0,0,14,0,16,16,0,17,18,0,0,0,0,0,0,0,0,0,0,0,20,0,22,0 },
            new int[] { 0,0,0,14,0,16,16,0,17,18,0,0,0,0,0,0,0,0,0,0,19,20,21,22,0 },
            new int[] { 0,0,0,29,0,16,16,0,17,30,0,0,0,0,0,0,0,0,0,0,31,0,0,22,0 },
            new int[] { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 },
            new int[] { 0,0,0,3,4,23,23,0,6,7,0,0,0,0,0,0,0,0,0,0,10,11,12,13,0 },
            new int[] { 0,0,0,0,0,23,23,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,0 },
            new int[] { 0,0,0,25,0,23,23,0,6,26,0,0,0,0,0,0,0,0,0,0,0,0,0,13,0 },
            new int[] { 0,0,0,25,0,23,23,0,6,26,0,0,0,0,0,0,0,0,0,0,27,0,0,13,0 },
            new int[] { 0,0,0,14,15,16,16,0,17,18,0,0,0,0,0,0,0,0,0,0,19,20,21,22,0 },
            new int[] { 0,0,0,0,0,16,16,0,17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22,0 },
            new int[] { 0,0,0,29,0,16,16,0,17,30,0,0,0,0,0,0,0,0,0,0,0,0,0,22,0 },
            new int[] { 0,0,0,29,0,16,16,0,17,30,0,0,0,0,0,0,0,0,0,0,31,0,0,22,0 }
        };

        public static bool[] AcceptingStates => new bool[]
        {
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true
        };

        public static string[][] Tags => new string[32][]
        {
            Array.Empty<string>(),
            new string[] { "broken_cluster" },
            new string[] { "consonant_syllable" },
            new string[] { "broken_cluster" },
            new string[] { "broken_cluster" },
            new string[] { "joiner_or_spacing_mark","broken_cluster" },
            new string[] { "broken_cluster" },
            new string[] { "broken_cluster" },
            new string[] { "consonant_syllable" },
            Array.Empty<string>(),
            new string[] { "broken_cluster" },
            new string[] { "broken_cluster" },
            new string[] { "broken_cluster" },
            new string[] { "broken_cluster" },
            new string[] { "consonant_syllable" },
            new string[] { "consonant_syllable" },
            new string[] { "consonant_syllable" },
            new string[] { "consonant_syllable" },
            new string[] { "consonant_syllable" },
            new string[] { "consonant_syllable" },
            new string[] { "consonant_syllable" },
            new string[] { "consonant_syllable" },
            new string[] { "consonant_syllable" },
            new string[] { "broken_cluster" },
            new string[] { "broken_cluster" },
            new string[] { "broken_cluster" },
            new string[] { "broken_cluster" },
            new string[] { "broken_cluster" },
            new string[] { "consonant_syllable" },
            new string[] { "consonant_syllable" },
            new string[] { "consonant_syllable" },
            new string[] { "consonant_syllable" }
        };
    }
}
