// Copyright (c) Six Labors.
// Licensed under the Six Labors Split License.

// <auto-generated />
namespace SixLabors.Fonts.Tables.AdvancedTypographic;

/// <content>
/// Contains the generated ISO 639 code to OpenType language system tag data.
/// </content>
internal sealed partial class OpenTypeLanguageTagMap
{
    /// <summary>
    /// Creates the map from lowercase ISO 639 codes to the OpenType language system
    /// tags registered for that language, in registry order with deprecated tags last.
    /// </summary>
    /// <returns>The populated map.</returns>
    private static Dictionary<string, Tag[]> CreateIsoLanguageMap()
        => new(StringComparer.Ordinal)
        {
            { "aae", new[] { Tag.Parse("SQI ") } }, // Albanian
            { "aao", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "aaq", new[] { Tag.Parse("AAQ ") } }, // Eastern Abenaki
            { "aar", new[] { Tag.Parse("AFR ") } }, // Afar
            { "aat", new[] { Tag.Parse("SQI ") } }, // Albanian
            { "abh", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "abk", new[] { Tag.Parse("ABK ") } }, // Abkhazian
            { "abq", new[] { Tag.Parse("ABA ") } }, // Abaza
            { "abs", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "abv", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "acf", new[] { Tag.Parse("CPP "), Tag.Parse("FAN ") } }, // Creoles; French Antillean
            { "ach", new[] { Tag.Parse("ACH ") } }, // Acholi
            { "acm", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "acq", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "acr", new[] { Tag.Parse("ACR "), Tag.Parse("MYN ") } }, // Achi; Mayan
            { "acw", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "acx", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "acy", new[] { Tag.Parse("ACY ") } }, // Cypriot Arabic
            { "ada", new[] { Tag.Parse("DNG ") } }, // Dangme
            { "adf", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "adp", new[] { Tag.Parse("DZN ") } }, // Dzongkha
            { "ady", new[] { Tag.Parse("ADY ") } }, // Adyghe
            { "aeb", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "aec", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "afb", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "afr", new[] { Tag.Parse("AFK ") } }, // Afrikaans
            { "afs", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "agu", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "ahg", new[] { Tag.Parse("AGW ") } }, // Agaw
            { "aht", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "aig", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "aii", new[] { Tag.Parse("SWA "), Tag.Parse("SYR ") } }, // Swadaya Aramaic; Syriac
            { "aio", new[] { Tag.Parse("AIO ") } }, // Aiton
            { "aiw", new[] { Tag.Parse("ARI ") } }, // Aari
            { "ajp", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "ajt", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "aka", new[] { Tag.Parse("AKA ") } }, // Akan
            { "akb", new[] { Tag.Parse("AKB "), Tag.Parse("BTK ") } }, // Batak Angkola; Batak languages
            { "aln", new[] { Tag.Parse("SQI ") } }, // Albanian
            { "als", new[] { Tag.Parse("SQI ") } }, // Albanian
            { "alt", new[] { Tag.Parse("ALT ") } }, // Altai
            { "amf", new[] { Tag.Parse("HBN ") } }, // Hammer-Banna
            { "amh", new[] { Tag.Parse("AMH ") } }, // Amharic
            { "amw", new[] { Tag.Parse("SYR ") } }, // Syriac
            { "ang", new[] { Tag.Parse("ANG ") } }, // Anglo-Saxon
            { "aoa", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "apa", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "apc", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "apd", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "apj", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "apk", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "apl", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "apm", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "apw", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "ara", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "arb", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "arg", new[] { Tag.Parse("ARG ") } }, // Aragonese
            { "arn", new[] { Tag.Parse("MAP ") } }, // Mapudungun
            { "arq", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "ars", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "ary", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "arz", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "asm", new[] { Tag.Parse("ASM ") } }, // Assamese
            { "ast", new[] { Tag.Parse("AST ") } }, // Asturian
            { "ath", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "atj", new[] { Tag.Parse("RCR ") } }, // R-Cree
            { "ats", new[] { Tag.Parse("ATS ") } }, // Gros Ventre (Atsina)
            { "atv", new[] { Tag.Parse("ALT ") } }, // Altai
            { "auj", new[] { Tag.Parse("BBR ") } }, // Berber
            { "auz", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "ava", new[] { Tag.Parse("AVR ") } }, // Avar
            { "avl", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "avn", new[] { Tag.Parse("AVN ") } }, // Avatime
            { "awa", new[] { Tag.Parse("AWA ") } }, // Awadhi
            { "ayc", new[] { Tag.Parse("AYM ") } }, // Aymara
            { "ayh", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "ayl", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "aym", new[] { Tag.Parse("AYM ") } }, // Aymara
            { "ayn", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "ayp", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "ayr", new[] { Tag.Parse("AYM ") } }, // Aymara
            { "azb", new[] { Tag.Parse("AZB ") } }, // Torki
            { "azd", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "aze", new[] { Tag.Parse("AZE ") } }, // Azerbaijani
            { "azj", new[] { Tag.Parse("AZE ") } }, // Azerbaijani
            { "azn", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "azz", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "bad", new[] { Tag.Parse("BAD0") } }, // Banda
            { "bah", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "bai", new[] { Tag.Parse("BML ") } }, // Bamileke
            { "bak", new[] { Tag.Parse("BSH ") } }, // Bashkir
            { "bal", new[] { Tag.Parse("BLI ") } }, // Baluchi
            { "bam", new[] { Tag.Parse("BMB ") } }, // Bambara (Bamanankan)
            { "ban", new[] { Tag.Parse("BAN ") } }, // Balinese
            { "bar", new[] { Tag.Parse("BAR ") } }, // Bavarian
            { "bbc", new[] { Tag.Parse("BBC "), Tag.Parse("BTK ") } }, // Batak Toba; Batak languages
            { "bbj", new[] { Tag.Parse("BML ") } }, // Bamileke
            { "bbp", new[] { Tag.Parse("BAD0") } }, // Banda
            { "bbz", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "bcc", new[] { Tag.Parse("BLI ") } }, // Baluchi
            { "bci", new[] { Tag.Parse("BAU ") } }, // Baulé
            { "bcl", new[] { Tag.Parse("BIK ") } }, // Bikol
            { "bcq", new[] { Tag.Parse("BCH ") } }, // Bench
            { "bcr", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "bdc", new[] { Tag.Parse("BDC ") } }, // Emberá-Baudó
            { "bdy", new[] { Tag.Parse("BDY ") } }, // Bandjalang
            { "bea", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "beb", new[] { Tag.Parse("BTI ") } }, // Beti
            { "bel", new[] { Tag.Parse("BEL ") } }, // Belarusian
            { "bem", new[] { Tag.Parse("BEM ") } }, // Bemba
            { "ben", new[] { Tag.Parse("BEN ") } }, // Bangla
            { "ber", new[] { Tag.Parse("BBR ") } }, // Berber
            { "bew", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "bfl", new[] { Tag.Parse("BAD0") } }, // Banda
            { "bfq", new[] { Tag.Parse("BAD ") } }, // Badaga
            { "bft", new[] { Tag.Parse("BLT ") } }, // Balti
            { "bfu", new[] { Tag.Parse("LAH ") } }, // Lahuli
            { "bfy", new[] { Tag.Parse("BAG ") } }, // Baghelkhandi
            { "bgc", new[] { Tag.Parse("BGC ") } }, // Haryanvi
            { "bgn", new[] { Tag.Parse("BLI ") } }, // Baluchi
            { "bgp", new[] { Tag.Parse("BLI ") } }, // Baluchi
            { "bgq", new[] { Tag.Parse("BGQ ") } }, // Bagri
            { "bgr", new[] { Tag.Parse("QIN ") } }, // Chin
            { "bhb", new[] { Tag.Parse("BHI ") } }, // Bhili
            { "bhi", new[] { Tag.Parse("BHI ") } }, // Bhili
            { "bhk", new[] { Tag.Parse("BIK ") } }, // Bikol
            { "bho", new[] { Tag.Parse("BHO ") } }, // Bhojpuri
            { "bhr", new[] { Tag.Parse("MLG ") } }, // Malagasy
            { "bik", new[] { Tag.Parse("BIK ") } }, // Bikol
            { "bin", new[] { Tag.Parse("EDO ") } }, // Edo
            { "bis", new[] { Tag.Parse("BIS "), Tag.Parse("CPP ") } }, // Bislama; Creoles
            { "biu", new[] { Tag.Parse("QIN ") } }, // Chin
            { "bjj", new[] { Tag.Parse("BJJ ") } }, // Kanauji
            { "bjn", new[] { Tag.Parse("MLY ") } }, // Malay
            { "bjo", new[] { Tag.Parse("BAD0") } }, // Banda
            { "bjq", new[] { Tag.Parse("MLG ") } }, // Malagasy
            { "bjs", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "bjt", new[] { Tag.Parse("BLN ") } }, // Balante
            { "bko", new[] { Tag.Parse("BML ") } }, // Bamileke
            { "bla", new[] { Tag.Parse("BKF ") } }, // Blackfoot
            { "ble", new[] { Tag.Parse("BLN ") } }, // Balante
            { "blg", new[] { Tag.Parse("IBA ") } }, // Iban
            { "blk", new[] { Tag.Parse("BLK "), Tag.Parse("KRN ") } }, // Pa’o Karen; Karen
            { "bln", new[] { Tag.Parse("BIK ") } }, // Bikol
            { "bmm", new[] { Tag.Parse("MLG ") } }, // Malagasy
            { "bod", new[] { Tag.Parse("TIB ") } }, // Tibetan
            { "bos", new[] { Tag.Parse("BOS ") } }, // Bosnian
            { "bpd", new[] { Tag.Parse("BAD0") } }, // Banda
            { "bpl", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "bpq", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "bpy", new[] { Tag.Parse("BPY ") } }, // Bishnupriya Manipuri
            { "bqi", new[] { Tag.Parse("LRC ") } }, // Luri
            { "bqk", new[] { Tag.Parse("BAD0") } }, // Banda
            { "bra", new[] { Tag.Parse("BRI ") } }, // Braj Bhasha
            { "brc", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "bre", new[] { Tag.Parse("BRE ") } }, // Breton
            { "brh", new[] { Tag.Parse("BRH ") } }, // Brahui
            { "brx", new[] { Tag.Parse("BRX ") } }, // Bodo
            { "bs", new[] { Tag.Parse("SRB ") } }, // Serbian
            { "bsk", new[] { Tag.Parse("BSK ") } }, // Burushaski
            { "btb", new[] { Tag.Parse("BTI ") } }, // Beti
            { "btd", new[] { Tag.Parse("BTD "), Tag.Parse("BTK ") } }, // Batak Dairi (Pakpak); Batak languages
            { "btj", new[] { Tag.Parse("MLY ") } }, // Malay
            { "btk", new[] { Tag.Parse("BTK ") } }, // Batak languages
            { "btm", new[] { Tag.Parse("BTK "), Tag.Parse("BTM ") } }, // Batak languages; Batak Mandailing
            { "bto", new[] { Tag.Parse("BIK ") } }, // Bikol
            { "bts", new[] { Tag.Parse("BTK "), Tag.Parse("BTS ") } }, // Batak languages; Batak Simalungun
            { "btx", new[] { Tag.Parse("BTK "), Tag.Parse("BTX ") } }, // Batak languages; Batak Karo
            { "btz", new[] { Tag.Parse("BTK "), Tag.Parse("BTZ ") } }, // Batak languages; Batak Alas-Kluet
            { "bug", new[] { Tag.Parse("BUG ") } }, // Bugis
            { "bul", new[] { Tag.Parse("BGR ") } }, // Bulgarian
            { "bum", new[] { Tag.Parse("BTI ") } }, // Beti
            { "bve", new[] { Tag.Parse("MLY ") } }, // Malay
            { "bvu", new[] { Tag.Parse("MLY ") } }, // Malay
            { "bwe", new[] { Tag.Parse("KRN ") } }, // Karen
            { "bxk", new[] { Tag.Parse("LUH ") } }, // Luyia
            { "bxo", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "bxp", new[] { Tag.Parse("BTI ") } }, // Beti
            { "bxr", new[] { Tag.Parse("RBU ") } }, // Russian Buriat
            { "byn", new[] { Tag.Parse("BIL ") } }, // Bilen
            { "byv", new[] { Tag.Parse("BML "), Tag.Parse("BYV ") } }, // Bamileke; Medumba
            { "bzc", new[] { Tag.Parse("MLG ") } }, // Malagasy
            { "bzj", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "bzk", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "caa", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "cac", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "caf", new[] { Tag.Parse("ATH "), Tag.Parse("CRR ") } }, // Athapaskan languages; Carrier
            { "cak", new[] { Tag.Parse("CAK "), Tag.Parse("MYN ") } }, // Kaqchikel; Mayan
            { "cat", new[] { Tag.Parse("CAT ") } }, // Catalan
            { "cay", new[] { Tag.Parse("CAY ") } }, // Cayuga
            { "cbg", new[] { Tag.Parse("CBG ") } }, // Chimila
            { "cbk", new[] { Tag.Parse("CBK "), Tag.Parse("CPP ") } }, // Zamboanga Chavacano; Creoles
            { "cbl", new[] { Tag.Parse("QIN ") } }, // Chin
            { "ccl", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "ccm", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "cco", new[] { Tag.Parse("CCHN") } }, // Chinantec
            { "ccq", new[] { Tag.Parse("ARK ") } }, // Rakhine
            { "ceb", new[] { Tag.Parse("CEB ") } }, // Cebuano
            { "cek", new[] { Tag.Parse("QIN ") } }, // Chin
            { "ces", new[] { Tag.Parse("CSY ") } }, // Czech
            { "cey", new[] { Tag.Parse("QIN ") } }, // Chin
            { "cfm", new[] { Tag.Parse("HAL "), Tag.Parse("QIN ") } }, // Halam (Falam Chin); Chin
            { "cgg", new[] { Tag.Parse("CGG ") } }, // Chiga
            { "cha", new[] { Tag.Parse("CHA ") } }, // Chamorro
            { "che", new[] { Tag.Parse("CHE ") } }, // Chechen
            { "chf", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "chj", new[] { Tag.Parse("CCHN") } }, // Chinantec
            { "chk", new[] { Tag.Parse("CHK0") } }, // Chuukese
            { "chn", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "cho", new[] { Tag.Parse("CHO ") } }, // Choctaw
            { "chp", new[] { Tag.Parse("ATH "), Tag.Parse("CHP "), Tag.Parse("SAY ") } }, // Athapaskan languages; Chipewyan; Sayisi
            { "chq", new[] { Tag.Parse("CCHN") } }, // Chinantec
            { "chr", new[] { Tag.Parse("CHR ") } }, // Cherokee
            { "chu", new[] { Tag.Parse("CSL ") } }, // Church Slavonic
            { "chv", new[] { Tag.Parse("CHU ") } }, // Chuvash
            { "chy", new[] { Tag.Parse("CHY ") } }, // Cheyenne
            { "chz", new[] { Tag.Parse("CCHN") } }, // Chinantec
            { "ciw", new[] { Tag.Parse("OJB ") } }, // Ojibway
            { "cja", new[] { Tag.Parse("CJA ") } }, // Western Cham
            { "cjm", new[] { Tag.Parse("CJM ") } }, // Eastern Cham
            { "cka", new[] { Tag.Parse("QIN ") } }, // Chin
            { "ckb", new[] { Tag.Parse("KUR ") } }, // Kurdish
            { "ckn", new[] { Tag.Parse("QIN ") } }, // Chin
            { "cks", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "ckt", new[] { Tag.Parse("CHK ") } }, // Chukchi
            { "ckz", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "clc", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "cld", new[] { Tag.Parse("SYR ") } }, // Syriac
            { "cle", new[] { Tag.Parse("CCHN") } }, // Chinantec
            { "clj", new[] { Tag.Parse("QIN ") } }, // Chin
            { "cls", new[] { Tag.Parse("SAN ") } }, // Sanskrit
            { "clt", new[] { Tag.Parse("QIN ") } }, // Chin
            { "cmi", new[] { Tag.Parse("CMI ") } }, // Emberá-Chamí
            { "cmr", new[] { Tag.Parse("QIN ") } }, // Chin
            { "cnb", new[] { Tag.Parse("QIN ") } }, // Chin
            { "cnh", new[] { Tag.Parse("QIN ") } }, // Chin
            { "cnk", new[] { Tag.Parse("QIN ") } }, // Chin
            { "cnl", new[] { Tag.Parse("CCHN") } }, // Chinantec
            { "cnr", new[] { Tag.Parse("SRB ") } }, // Serbian
            { "cnt", new[] { Tag.Parse("CCHN") } }, // Chinantec
            { "cnu", new[] { Tag.Parse("BBR ") } }, // Berber
            { "cnw", new[] { Tag.Parse("QIN ") } }, // Chin
            { "coa", new[] { Tag.Parse("MLY ") } }, // Malay
            { "cob", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "coo", new[] { Tag.Parse("COO ") } }, // Comox
            { "cop", new[] { Tag.Parse("COP ") } }, // Coptic
            { "coq", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "cor", new[] { Tag.Parse("COR ") } }, // Cornish
            { "cos", new[] { Tag.Parse("COS ") } }, // Corsican
            { "cpa", new[] { Tag.Parse("CCHN") } }, // Chinantec
            { "cpe", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "cpf", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "cpi", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "cpp", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "cqd", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "cqu", new[] { Tag.Parse("QUH ") } }, // Quechua (Bolivia)
            { "cre", new[] { Tag.Parse("CRE ") } }, // Cree
            { "crh", new[] { Tag.Parse("CRT ") } }, // Crimean Tatar
            { "cri", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "crj", new[] { Tag.Parse("ECR "), Tag.Parse("YCR ") } }, // Eastern Cree; Y-Cree
            { "crk", new[] { Tag.Parse("WCR "), Tag.Parse("YCR ") } }, // West-Cree; Y-Cree
            { "crl", new[] { Tag.Parse("ECR "), Tag.Parse("YCR ") } }, // Eastern Cree; Y-Cree
            { "crm", new[] { Tag.Parse("LCR "), Tag.Parse("MCR ") } }, // L-Cree; Moose Cree
            { "crp", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "crs", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "crx", new[] { Tag.Parse("ATH "), Tag.Parse("CRR ") } }, // Athapaskan languages; Carrier
            { "csa", new[] { Tag.Parse("CCHN") } }, // Chinantec
            { "csb", new[] { Tag.Parse("CSB ") } }, // Kashubian
            { "csh", new[] { Tag.Parse("QIN ") } }, // Chin
            { "csj", new[] { Tag.Parse("QIN ") } }, // Chin
            { "cso", new[] { Tag.Parse("CCHN") } }, // Chinantec
            { "csv", new[] { Tag.Parse("QIN ") } }, // Chin
            { "csw", new[] { Tag.Parse("NCR "), Tag.Parse("NHC ") } }, // N-Cree; Norway House Cree
            { "csy", new[] { Tag.Parse("QIN ") } }, // Chin
            { "ctc", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "ctd", new[] { Tag.Parse("QIN ") } }, // Chin
            { "cte", new[] { Tag.Parse("CCHN") } }, // Chinantec
            { "ctg", new[] { Tag.Parse("CTG ") } }, // Chittagonian
            { "cth", new[] { Tag.Parse("QIN ") } }, // Chin
            { "ctl", new[] { Tag.Parse("CCHN") } }, // Chinantec
            { "cto", new[] { Tag.Parse("CTO ") } }, // Emberá-Catío
            { "cts", new[] { Tag.Parse("BIK ") } }, // Bikol
            { "ctt", new[] { Tag.Parse("CTT ") } }, // Wayanad Chetti
            { "ctu", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "cuc", new[] { Tag.Parse("CCHN") } }, // Chinantec
            { "cuk", new[] { Tag.Parse("CUK ") } }, // San Blas Kuna
            { "cvn", new[] { Tag.Parse("CCHN") } }, // Chinantec
            { "cwd", new[] { Tag.Parse("DCR "), Tag.Parse("TCR ") } }, // Woods Cree; TH-Cree
            { "cym", new[] { Tag.Parse("WEL ") } }, // Welsh
            { "czt", new[] { Tag.Parse("QIN ") } }, // Chin
            { "dag", new[] { Tag.Parse("DAG ") } }, // Dagbani
            { "dan", new[] { Tag.Parse("DAN ") } }, // Danish
            { "dao", new[] { Tag.Parse("QIN ") } }, // Chin
            { "dap", new[] { Tag.Parse("NIS ") } }, // Nisi
            { "dar", new[] { Tag.Parse("DAR ") } }, // Dargwa
            { "dax", new[] { Tag.Parse("DAX ") } }, // Dayi
            { "dcr", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "den", new[] { Tag.Parse("ATH "), Tag.Parse("SLA ") } }, // Athapaskan languages; Slavey
            { "dep", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "deu", new[] { Tag.Parse("DEU ") } }, // German
            { "dgo", new[] { Tag.Parse("DGO ") } }, // Dogri (individual language)
            { "dgr", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "dhd", new[] { Tag.Parse("MAW ") } }, // Marwari
            { "dhg", new[] { Tag.Parse("DHG ") } }, // Dhangu
            { "dib", new[] { Tag.Parse("DNK ") } }, // Dinka
            { "dik", new[] { Tag.Parse("DNK ") } }, // Dinka
            { "din", new[] { Tag.Parse("DNK ") } }, // Dinka
            { "dip", new[] { Tag.Parse("DNK ") } }, // Dinka
            { "diq", new[] { Tag.Parse("DIQ ") } }, // Dimli
            { "div", new[] { Tag.Parse("DIV "), Tag.Parse("DHV ") } }, // Divehi (Dhivehi, Maldivian)
            { "diw", new[] { Tag.Parse("DNK ") } }, // Dinka
            { "dje", new[] { Tag.Parse("DJR ") } }, // Zarma
            { "djk", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "djr", new[] { Tag.Parse("DJR0") } }, // Djambarrpuyngu
            { "dks", new[] { Tag.Parse("DNK ") } }, // Dinka
            { "dng", new[] { Tag.Parse("DUN ") } }, // Dungan
            { "dnj", new[] { Tag.Parse("DNJ ") } }, // Dan
            { "doi", new[] { Tag.Parse("DGR ") } }, // Dogri (macrolanguage)
            { "drw", new[] { Tag.Parse("DRI ") } }, // Dari
            { "dsb", new[] { Tag.Parse("LSB ") } }, // Lower Sorbian
            { "dty", new[] { Tag.Parse("NEP ") } }, // Nepali
            { "duj", new[] { Tag.Parse("DUJ ") } }, // Dhuwal
            { "dup", new[] { Tag.Parse("MLY ") } }, // Malay
            { "dwu", new[] { Tag.Parse("DUJ ") } }, // Dhuwal
            { "dwy", new[] { Tag.Parse("DUJ ") } }, // Dhuwal
            { "dyu", new[] { Tag.Parse("JUL ") } }, // Jula
            { "dzo", new[] { Tag.Parse("DZN ") } }, // Dzongkha
            { "efi", new[] { Tag.Parse("EFI ") } }, // Efik
            { "ekk", new[] { Tag.Parse("ETI ") } }, // Estonian
            { "eky", new[] { Tag.Parse("KRN ") } }, // Karen
            { "ell", new[] { Tag.Parse("ELL "), Tag.Parse("PGR ") } }, // Greek; Polytonic Greek
            { "emk", new[] { Tag.Parse("EMK "), Tag.Parse("MNK ") } }, // Eastern Maninkakan; Maninka
            { "emp", new[] { Tag.Parse("EMP ") } }, // Northern Emberá
            { "emy", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "enb", new[] { Tag.Parse("KAL ") } }, // Kalenjin
            { "enf", new[] { Tag.Parse("FNE ") } }, // Forest Enets
            { "eng", new[] { Tag.Parse("ENG ") } }, // English
            { "enh", new[] { Tag.Parse("TNE ") } }, // Tundra Enets
            { "epo", new[] { Tag.Parse("NTO ") } }, // Esperanto
            { "esg", new[] { Tag.Parse("GON ") } }, // Gondi
            { "esi", new[] { Tag.Parse("IPK ") } }, // Inupiat
            { "esk", new[] { Tag.Parse("IPK ") } }, // Inupiat
            { "est", new[] { Tag.Parse("ETI ") } }, // Estonian
            { "esu", new[] { Tag.Parse("ESU ") } }, // Central Yupik
            { "eto", new[] { Tag.Parse("BTI ") } }, // Beti
            { "eus", new[] { Tag.Parse("EUQ ") } }, // Basque
            { "eve", new[] { Tag.Parse("EVN ") } }, // Even
            { "evn", new[] { Tag.Parse("EVK ") } }, // Evenki
            { "ewe", new[] { Tag.Parse("EWE ") } }, // Ewe
            { "ewo", new[] { Tag.Parse("BTI ") } }, // Beti
            { "eyo", new[] { Tag.Parse("KAL ") } }, // Kalenjin
            { "fab", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "fan", new[] { Tag.Parse("FAN0") } }, // Fang
            { "fao", new[] { Tag.Parse("FOS ") } }, // Faroese
            { "fas", new[] { Tag.Parse("FAR ") } }, // Persian
            { "fat", new[] { Tag.Parse("AKA "), Tag.Parse("FAT ") } }, // Akan; Fanti
            { "fbl", new[] { Tag.Parse("BIK ") } }, // Bikol
            { "ffm", new[] { Tag.Parse("FUL ") } }, // Fulah
            { "fij", new[] { Tag.Parse("FJI ") } }, // Fijian
            { "fil", new[] { Tag.Parse("PIL ") } }, // Filipino
            { "fin", new[] { Tag.Parse("FIN ") } }, // Finnish
            { "fmp", new[] { Tag.Parse("BML "), Tag.Parse("FMP ") } }, // Bamileke; Fe’fe’
            { "fng", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "fon", new[] { Tag.Parse("FON ") } }, // Fon
            { "fpe", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "fra", new[] { Tag.Parse("FRA ") } }, // French
            { "frc", new[] { Tag.Parse("FRC ") } }, // Cajun French
            { "frp", new[] { Tag.Parse("FRP ") } }, // Arpitan
            { "fry", new[] { Tag.Parse("FRI ") } }, // Frisian
            { "fub", new[] { Tag.Parse("FUL ") } }, // Fulah
            { "fuc", new[] { Tag.Parse("FUL ") } }, // Fulah
            { "fue", new[] { Tag.Parse("FUL ") } }, // Fulah
            { "fuf", new[] { Tag.Parse("FTA ") } }, // Futa
            { "fuh", new[] { Tag.Parse("FUL ") } }, // Fulah
            { "fui", new[] { Tag.Parse("FUL ") } }, // Fulah
            { "ful", new[] { Tag.Parse("FUL ") } }, // Fulah
            { "fuq", new[] { Tag.Parse("FUL ") } }, // Fulah
            { "fur", new[] { Tag.Parse("FRL ") } }, // Friulian
            { "fuv", new[] { Tag.Parse("FUV ") } }, // Nigerian Fulfulde
            { "gaa", new[] { Tag.Parse("GAD ") } }, // Ga
            { "gac", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "gag", new[] { Tag.Parse("GAG ") } }, // Gagauz
            { "gax", new[] { Tag.Parse("ORO ") } }, // Oromo
            { "gaz", new[] { Tag.Parse("ORO ") } }, // Oromo
            { "gbm", new[] { Tag.Parse("GAW ") } }, // Garhwali
            { "gce", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "gcf", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "gcl", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "gcr", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "gda", new[] { Tag.Parse("RAJ ") } }, // Rajasthani
            { "gez", new[] { Tag.Parse("GEZ ") } }, // Geez
            { "gha", new[] { Tag.Parse("BBR ") } }, // Berber
            { "ghc", new[] { Tag.Parse("IRT ") } }, // Irish Traditional
            { "ghk", new[] { Tag.Parse("KRN ") } }, // Karen
            { "gho", new[] { Tag.Parse("BBR ") } }, // Berber
            { "gib", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "gih", new[] { Tag.Parse("GIH ") } }, // Githabul
            { "gil", new[] { Tag.Parse("GIL0") } }, // Kiribati (Gilbertese)
            { "gju", new[] { Tag.Parse("RAJ ") } }, // Rajasthani
            { "gkp", new[] { Tag.Parse("GKP ") } }, // Kpelle (Guinea)
            { "gla", new[] { Tag.Parse("GAE ") } }, // Scottish Gaelic
            { "gld", new[] { Tag.Parse("NAN ") } }, // Nanai
            { "gle", new[] { Tag.Parse("IRI "), Tag.Parse("IRT ") } }, // Irish; Irish Traditional
            { "glg", new[] { Tag.Parse("GAL ") } }, // Galician
            { "glk", new[] { Tag.Parse("GLK ") } }, // Gilaki
            { "glv", new[] { Tag.Parse("MNX ") } }, // Manx
            { "gnb", new[] { Tag.Parse("QIN ") } }, // Chin
            { "gnn", new[] { Tag.Parse("GNN ") } }, // Gumatj
            { "gno", new[] { Tag.Parse("GON ") } }, // Gondi
            { "gnw", new[] { Tag.Parse("GUA ") } }, // Guarani
            { "gog", new[] { Tag.Parse("GOG ") } }, // Gogo
            { "gom", new[] { Tag.Parse("KOK ") } }, // Konkani
            { "gon", new[] { Tag.Parse("GON ") } }, // Gondi
            { "goq", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "gox", new[] { Tag.Parse("BAD0") } }, // Banda
            { "gpe", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "grn", new[] { Tag.Parse("GUA ") } }, // Guarani
            { "grr", new[] { Tag.Parse("BBR ") } }, // Berber
            { "grt", new[] { Tag.Parse("GRO ") } }, // Garo
            { "gru", new[] { Tag.Parse("SOG ") } }, // Sodo Gurage
            { "gsw", new[] { Tag.Parse("ALS ") } }, // Alsatian
            { "guc", new[] { Tag.Parse("GUC ") } }, // Wayuu
            { "guf", new[] { Tag.Parse("GUF ") } }, // Gupapuyngu
            { "gug", new[] { Tag.Parse("GUA ") } }, // Guarani
            { "gui", new[] { Tag.Parse("GUA ") } }, // Guarani
            { "guj", new[] { Tag.Parse("GUJ ") } }, // Gujarati
            { "guk", new[] { Tag.Parse("GMZ ") } }, // Gumuz
            { "gul", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "gun", new[] { Tag.Parse("GUA ") } }, // Guarani
            { "guz", new[] { Tag.Parse("GUZ ") } }, // Gusii
            { "gwi", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "gyn", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "haa", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "hae", new[] { Tag.Parse("ORO ") } }, // Oromo
            { "hai", new[] { Tag.Parse("HAI0") } }, // Haida
            { "har", new[] { Tag.Parse("HRI ") } }, // Harari
            { "hat", new[] { Tag.Parse("CPP "), Tag.Parse("HAI ") } }, // Creoles; Haitian (Haitian Creole)
            { "hau", new[] { Tag.Parse("HAU ") } }, // Hausa
            { "haw", new[] { Tag.Parse("HAW ") } }, // Hawaiian
            { "hax", new[] { Tag.Parse("HAI0") } }, // Haida
            { "hay", new[] { Tag.Parse("HAY ") } }, // Haya
            { "haz", new[] { Tag.Parse("HAZ ") } }, // Hazaragi
            { "hca", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "hdn", new[] { Tag.Parse("HAI0") } }, // Haida
            { "hea", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "heb", new[] { Tag.Parse("IWR ") } }, // Hebrew
            { "hei", new[] { Tag.Parse("HEI ") } }, // Heiltsuk
            { "her", new[] { Tag.Parse("HER ") } }, // Herero
            { "hil", new[] { Tag.Parse("HIL ") } }, // Hiligaynon
            { "hin", new[] { Tag.Parse("HIN ") } }, // Hindi
            { "hji", new[] { Tag.Parse("MLY ") } }, // Malay
            { "hlt", new[] { Tag.Parse("QIN ") } }, // Chin
            { "hma", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "hmc", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "hmd", new[] { Tag.Parse("HMD ") } }, // A-Hmao
            { "hme", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "hmg", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "hmh", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "hmi", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "hmj", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "hml", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "hmm", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "hmn", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "hmo", new[] { Tag.Parse("CPP "), Tag.Parse("HMO ") } }, // Creoles; Hiri Motu
            { "hmp", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "hmq", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "hmr", new[] { Tag.Parse("QIN ") } }, // Chin
            { "hms", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "hmw", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "hmy", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "hmz", new[] { Tag.Parse("HMZ ") } }, // Hmong Shuat
            { "hnd", new[] { Tag.Parse("HND ") } }, // Hindko
            { "hne", new[] { Tag.Parse("CHH ") } }, // Chattisgarhi
            { "hnj", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "hno", new[] { Tag.Parse("HND ") } }, // Hindko
            { "hoc", new[] { Tag.Parse("HO  ") } }, // Ho
            { "hoi", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "hoj", new[] { Tag.Parse("HAR ") } }, // Harauti
            { "hr", new[] { Tag.Parse("SRB ") } }, // Serbian
            { "hra", new[] { Tag.Parse("QIN ") } }, // Chin
            { "hrm", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "hrv", new[] { Tag.Parse("HRV ") } }, // Croatian
            { "hsb", new[] { Tag.Parse("USB ") } }, // Upper Sorbian
            { "huj", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "hun", new[] { Tag.Parse("HUN ") } }, // Hungarian
            { "hup", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "hur", new[] { Tag.Parse("HUR ") } }, // Halkomelem
            { "hus", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "hwc", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "hye", new[] { Tag.Parse("HYE "), Tag.Parse("HYE0") } }, // Armenian; Armenian East
            { "hyw", new[] { Tag.Parse("HYE ") } }, // Armenian
            { "iba", new[] { Tag.Parse("IBA ") } }, // Iban
            { "ibb", new[] { Tag.Parse("IBB ") } }, // Ibibio
            { "ibo", new[] { Tag.Parse("IBO ") } }, // Igbo
            { "iby", new[] { Tag.Parse("IJO ") } }, // Ijo languages
            { "icr", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "id", new[] { Tag.Parse("MLY ") } }, // Malay
            { "ida", new[] { Tag.Parse("LUH ") } }, // Luyia
            { "idb", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "ido", new[] { Tag.Parse("IDO ") } }, // Ido
            { "igb", new[] { Tag.Parse("EBI ") } }, // Ebira
            { "ihb", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "iii", new[] { Tag.Parse("YIM ") } }, // Yi Modern
            { "ijc", new[] { Tag.Parse("IJO ") } }, // Ijo languages
            { "ije", new[] { Tag.Parse("IJO ") } }, // Ijo languages
            { "ijn", new[] { Tag.Parse("IJO ") } }, // Ijo languages
            { "ijo", new[] { Tag.Parse("IJO ") } }, // Ijo languages
            { "ijs", new[] { Tag.Parse("IJO ") } }, // Ijo languages
            { "ike", new[] { Tag.Parse("INUK") } }, // Nunavik Inuktitut
            { "ikt", new[] { Tag.Parse("INU "), Tag.Parse("INUK") } }, // Inuktitut; Nunavik Inuktitut
            { "iku", new[] { Tag.Parse("INU "), Tag.Parse("INUK") } }, // Inuktitut; Nunavik Inuktitut
            { "ile", new[] { Tag.Parse("ILE ") } }, // Interlingue
            { "ilo", new[] { Tag.Parse("ILO ") } }, // Ilokano
            { "in", new[] { Tag.Parse("MLY ") } }, // Malay
            { "ina", new[] { Tag.Parse("INA ") } }, // Interlingua
            { "ind", new[] { Tag.Parse("IND ") } }, // Indonesian
            { "ing", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "inh", new[] { Tag.Parse("ING ") } }, // Ingush
            { "ipk", new[] { Tag.Parse("IPK ") } }, // Inupiat
            { "iru", new[] { Tag.Parse("IRU ") } }, // Irula
            { "isl", new[] { Tag.Parse("ISL ") } }, // Icelandic
            { "ita", new[] { Tag.Parse("ITA ") } }, // Italian
            { "itz", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "iw", new[] { Tag.Parse("IWR ") } }, // Hebrew
            { "ixl", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "jac", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "jak", new[] { Tag.Parse("MLY ") } }, // Malay
            { "jam", new[] { Tag.Parse("CPP "), Tag.Parse("JAM ") } }, // Creoles; Jamaican Creole
            { "jav", new[] { Tag.Parse("JAV ") } }, // Javanese
            { "jax", new[] { Tag.Parse("MLY ") } }, // Malay
            { "jbe", new[] { Tag.Parse("BBR ") } }, // Berber
            { "jbn", new[] { Tag.Parse("BBR ") } }, // Berber
            { "jbo", new[] { Tag.Parse("JBO ") } }, // Lojban
            { "jct", new[] { Tag.Parse("JCT ") } }, // Krymchak
            { "jdt", new[] { Tag.Parse("JDT ") } }, // Judeo-Tat
            { "jgo", new[] { Tag.Parse("BML ") } }, // Bamileke
            { "ji", new[] { Tag.Parse("JII ") } }, // Yiddish
            { "jkm", new[] { Tag.Parse("KRN ") } }, // Karen
            { "jkp", new[] { Tag.Parse("KRN ") } }, // Karen
            { "jpn", new[] { Tag.Parse("JAN ") } }, // Japanese
            { "jvd", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "jw", new[] { Tag.Parse("JAV ") } }, // Javanese
            { "kaa", new[] { Tag.Parse("KRK ") } }, // Karakalpak
            { "kab", new[] { Tag.Parse("BBR "), Tag.Parse("KAB0") } }, // Berber; Kabyle
            { "kal", new[] { Tag.Parse("GRN ") } }, // Greenlandic
            { "kam", new[] { Tag.Parse("KMB ") } }, // Kamba
            { "kan", new[] { Tag.Parse("KAN ") } }, // Kannada
            { "kar", new[] { Tag.Parse("KRN ") } }, // Karen
            { "kas", new[] { Tag.Parse("KSH ") } }, // Kashmiri
            { "kat", new[] { Tag.Parse("KAT "), Tag.Parse("KGE ") } }, // Georgian; Khutsuri Georgian
            { "kau", new[] { Tag.Parse("KNR ") } }, // Kanuri
            { "kaw", new[] { Tag.Parse("KAW ") } }, // Kawi (Old Javanese)
            { "kaz", new[] { Tag.Parse("KAZ ") } }, // Kazakh
            { "kbc", new[] { Tag.Parse("KBC ") } }, // Kadiwéu
            { "kbd", new[] { Tag.Parse("KAB ") } }, // Kabardian
            { "kby", new[] { Tag.Parse("KNR ") } }, // Kanuri
            { "kca", new[] { Tag.Parse("KHK "), Tag.Parse("KHS "), Tag.Parse("KHV ") } }, // Khanty-Kazim; Khanty-Shurishkar; Khanty-Vakhi
            { "kcn", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "kde", new[] { Tag.Parse("KDE ") } }, // Makonde
            { "kdr", new[] { Tag.Parse("KRM ") } }, // Karaim
            { "kdt", new[] { Tag.Parse("KUY ") } }, // Kuy
            { "kea", new[] { Tag.Parse("CPP "), Tag.Parse("KEA ") } }, // Creoles; Kabuverdianu (Crioulo)
            { "kek", new[] { Tag.Parse("KEK "), Tag.Parse("MYN ") } }, // Kekchi; Mayan
            { "kex", new[] { Tag.Parse("KKN ") } }, // Kokni
            { "kfa", new[] { Tag.Parse("KOD ") } }, // Kodagu
            { "kfr", new[] { Tag.Parse("KAC ") } }, // Kachchi
            { "kfx", new[] { Tag.Parse("KUL ") } }, // Kulvi
            { "kfy", new[] { Tag.Parse("KMN ") } }, // Kumaoni
            { "kgf", new[] { Tag.Parse("KGF ") } }, // Kube
            { "kha", new[] { Tag.Parse("KSI ") } }, // Khasi
            { "khb", new[] { Tag.Parse("XBD ") } }, // Lü
            { "khk", new[] { Tag.Parse("MNG ") } }, // Mongolian
            { "khm", new[] { Tag.Parse("KHM ") } }, // Khmer
            { "kht", new[] { Tag.Parse("KHT ") } }, // Khamti Shan
            { "khw", new[] { Tag.Parse("KHW ") } }, // Khowar
            { "kik", new[] { Tag.Parse("KIK ") } }, // Kikuyu (Gikuyu)
            { "kin", new[] { Tag.Parse("RUA ") } }, // Kinyarwanda
            { "kir", new[] { Tag.Parse("KIR ") } }, // Kirghiz (Kyrgyz)
            { "kiu", new[] { Tag.Parse("KIU ") } }, // Kirmanjki
            { "kjb", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "kjd", new[] { Tag.Parse("KJD ") } }, // Southern Kiwai
            { "kjh", new[] { Tag.Parse("KHA ") } }, // Khakass
            { "kjj", new[] { Tag.Parse("KJJ ") } }, // Khinalug
            { "kjp", new[] { Tag.Parse("KJP "), Tag.Parse("KRN ") } }, // Eastern Pwo Karen; Karen
            { "kjt", new[] { Tag.Parse("KRN ") } }, // Karen
            { "kjz", new[] { Tag.Parse("KJZ ") } }, // Bumthangkha
            { "kkz", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "kln", new[] { Tag.Parse("KAL ") } }, // Kalenjin
            { "kmb", new[] { Tag.Parse("MBN ") } }, // Mbundu
            { "kmg", new[] { Tag.Parse("KMG ") } }, // Kâte
            { "kmr", new[] { Tag.Parse("KUR ") } }, // Kurdish
            { "kmv", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "kmw", new[] { Tag.Parse("KMO ") } }, // Komo
            { "kmz", new[] { Tag.Parse("KMZ ") } }, // Khorasani Turkic
            { "knc", new[] { Tag.Parse("KNR ") } }, // Kanuri
            { "kng", new[] { Tag.Parse("KON0") } }, // Kongo
            { "knj", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "knn", new[] { Tag.Parse("KOK ") } }, // Konkani
            { "koi", new[] { Tag.Parse("KOP ") } }, // Komi-Permyak
            { "kok", new[] { Tag.Parse("KOK ") } }, // Konkani
            { "kom", new[] { Tag.Parse("KOM ") } }, // Komi
            { "kon", new[] { Tag.Parse("KON0") } }, // Kongo
            { "kor", new[] { Tag.Parse("KOH "), Tag.Parse("KOR ") } }, // Korean Old Hangul; Korean
            { "kos", new[] { Tag.Parse("KOS ") } }, // Kosraean
            { "koy", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "kpe", new[] { Tag.Parse("KPL ") } }, // Kpelle
            { "kpv", new[] { Tag.Parse("KOZ ") } }, // Komi-Zyrian
            { "kpy", new[] { Tag.Parse("KYK ") } }, // Koryak
            { "kqs", new[] { Tag.Parse("KIS ") } }, // Kisii
            { "kqy", new[] { Tag.Parse("KRT ") } }, // Koorete
            { "krc", new[] { Tag.Parse("BAL "), Tag.Parse("KAR ") } }, // Balkar; Karachay
            { "kri", new[] { Tag.Parse("CPP "), Tag.Parse("KRI ") } }, // Creoles; Krio
            { "krl", new[] { Tag.Parse("KRL ") } }, // Karelian
            { "krt", new[] { Tag.Parse("KNR ") } }, // Kanuri
            { "kru", new[] { Tag.Parse("KUU ") } }, // Kurukh
            { "ksh", new[] { Tag.Parse("KSH0") } }, // Ripuarian
            { "kss", new[] { Tag.Parse("KIS ") } }, // Kisii
            { "ksu", new[] { Tag.Parse("KSU ") } }, // Khamyang
            { "ksw", new[] { Tag.Parse("KRN "), Tag.Parse("KSW ") } }, // Karen; S’gaw Karen
            { "ktb", new[] { Tag.Parse("KEB ") } }, // Kebena
            { "ktu", new[] { Tag.Parse("KON ") } }, // Kikongo
            { "ktw", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "kua", new[] { Tag.Parse("KUA ") } }, // Kuanyama
            { "kum", new[] { Tag.Parse("KUM ") } }, // Kumyk
            { "kur", new[] { Tag.Parse("KUR ") } }, // Kurdish
            { "kuu", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "kuw", new[] { Tag.Parse("BAD0") } }, // Banda
            { "kvb", new[] { Tag.Parse("MLY ") } }, // Malay
            { "kvl", new[] { Tag.Parse("KRN ") } }, // Karen
            { "kvq", new[] { Tag.Parse("KRN "), Tag.Parse("KVQ ") } }, // Karen; Geba Karen
            { "kvr", new[] { Tag.Parse("MLY ") } }, // Malay
            { "kvt", new[] { Tag.Parse("KRN ") } }, // Karen
            { "kvu", new[] { Tag.Parse("KRN ") } }, // Karen
            { "kvy", new[] { Tag.Parse("KRN ") } }, // Karen
            { "kwk", new[] { Tag.Parse("KWK ") } }, // Kwakʼwala
            { "kww", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "kwy", new[] { Tag.Parse("KON0") } }, // Kongo
            { "kxc", new[] { Tag.Parse("KMS ") } }, // Komso
            { "kxd", new[] { Tag.Parse("MLY ") } }, // Malay
            { "kxf", new[] { Tag.Parse("KRN ") } }, // Karen
            { "kxk", new[] { Tag.Parse("KRN ") } }, // Karen
            { "kxl", new[] { Tag.Parse("KUU ") } }, // Kurukh
            { "kxu", new[] { Tag.Parse("KUI ") } }, // Kui
            { "kyu", new[] { Tag.Parse("KRN "), Tag.Parse("KYU ") } }, // Karen; Western Kayah
            { "lac", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "lad", new[] { Tag.Parse("JUD ") } }, // Ladino
            { "lao", new[] { Tag.Parse("LAO ") } }, // Lao
            { "lat", new[] { Tag.Parse("LAT ") } }, // Latin
            { "lav", new[] { Tag.Parse("LVI ") } }, // Latvian
            { "lbe", new[] { Tag.Parse("LAK ") } }, // Lak
            { "lbj", new[] { Tag.Parse("LDK ") } }, // Ladakhi
            { "lbl", new[] { Tag.Parse("BIK ") } }, // Bikol
            { "lce", new[] { Tag.Parse("MLY ") } }, // Malay
            { "lcf", new[] { Tag.Parse("MLY ") } }, // Malay
            { "ldi", new[] { Tag.Parse("KON0") } }, // Kongo
            { "lef", new[] { Tag.Parse("LEF ") } }, // Lelemi
            { "lez", new[] { Tag.Parse("LEZ ") } }, // Lezgi
            { "lif", new[] { Tag.Parse("LMB ") } }, // Limbu
            { "lij", new[] { Tag.Parse("LIJ ") } }, // Ligurian
            { "lim", new[] { Tag.Parse("LIM ") } }, // Limburgish
            { "lin", new[] { Tag.Parse("LIN ") } }, // Lingala
            { "lir", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "lis", new[] { Tag.Parse("LIS ") } }, // Lisu
            { "lit", new[] { Tag.Parse("LTH ") } }, // Lithuanian
            { "liv", new[] { Tag.Parse("LIV ") } }, // Liv
            { "liw", new[] { Tag.Parse("MLY ") } }, // Malay
            { "liy", new[] { Tag.Parse("BAD0") } }, // Banda
            { "ljp", new[] { Tag.Parse("LJP ") } }, // Lampung
            { "lkb", new[] { Tag.Parse("LUH ") } }, // Luyia
            { "lki", new[] { Tag.Parse("LKI ") } }, // Laki
            { "lko", new[] { Tag.Parse("LUH ") } }, // Luyia
            { "lks", new[] { Tag.Parse("LUH ") } }, // Luyia
            { "lld", new[] { Tag.Parse("LAD ") } }, // Ladin
            { "lmn", new[] { Tag.Parse("LAM ") } }, // Lambani
            { "lmo", new[] { Tag.Parse("LMO ") } }, // Lombard
            { "lna", new[] { Tag.Parse("BAD0") } }, // Banda
            { "lnl", new[] { Tag.Parse("BAD0") } }, // Banda
            { "lom", new[] { Tag.Parse("LOM ") } }, // Loma
            { "lou", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "lpo", new[] { Tag.Parse("LPO ") } }, // Lipo
            { "lrc", new[] { Tag.Parse("LRC ") } }, // Luri
            { "lri", new[] { Tag.Parse("LUH ") } }, // Luyia
            { "lrm", new[] { Tag.Parse("LUH ") } }, // Luyia
            { "lrt", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "lsm", new[] { Tag.Parse("LUH ") } }, // Luyia
            { "ltg", new[] { Tag.Parse("LVI ") } }, // Latvian
            { "lto", new[] { Tag.Parse("LUH ") } }, // Luyia
            { "lts", new[] { Tag.Parse("LUH ") } }, // Luyia
            { "ltz", new[] { Tag.Parse("LTZ ") } }, // Luxembourgish
            { "lua", new[] { Tag.Parse("LUA ") } }, // Luba-Lulua
            { "lub", new[] { Tag.Parse("LUB ") } }, // Luba-Katanga
            { "lug", new[] { Tag.Parse("LUG ") } }, // Ganda
            { "luo", new[] { Tag.Parse("LUO ") } }, // Luo
            { "lus", new[] { Tag.Parse("MIZ "), Tag.Parse("QIN ") } }, // Mizo; Chin
            { "lut", new[] { Tag.Parse("LUT ") } }, // Lushootseed
            { "luy", new[] { Tag.Parse("LUH ") } }, // Luyia
            { "luz", new[] { Tag.Parse("LRC ") } }, // Luri
            { "lvs", new[] { Tag.Parse("LVI ") } }, // Latvian
            { "lwg", new[] { Tag.Parse("LUH ") } }, // Luyia
            { "lzz", new[] { Tag.Parse("LAZ ") } }, // Laz
            { "mad", new[] { Tag.Parse("MAD ") } }, // Madura
            { "mag", new[] { Tag.Parse("MAG ") } }, // Magahi
            { "mah", new[] { Tag.Parse("MAH ") } }, // Marshallese
            { "mai", new[] { Tag.Parse("MTH ") } }, // Maithili
            { "mak", new[] { Tag.Parse("MKR ") } }, // Makasar
            { "mal", new[] { Tag.Parse("MAL "), Tag.Parse("MLR ") } }, // Malayalam; Malayalam Reformed
            { "mam", new[] { Tag.Parse("MAM "), Tag.Parse("MYN ") } }, // Mam; Mayan
            { "man", new[] { Tag.Parse("MNK ") } }, // Maninka
            { "mar", new[] { Tag.Parse("MAR ") } }, // Marathi
            { "max", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "mbf", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "mbo", new[] { Tag.Parse("MBO ") } }, // Mbo
            { "mcm", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "mct", new[] { Tag.Parse("BTI ") } }, // Beti
            { "mdf", new[] { Tag.Parse("MOK ") } }, // Moksha
            { "mdr", new[] { Tag.Parse("MDR ") } }, // Mandar
            { "mdy", new[] { Tag.Parse("MLE ") } }, // Male
            { "men", new[] { Tag.Parse("MDE ") } }, // Mende
            { "meo", new[] { Tag.Parse("MLY ") } }, // Malay
            { "mer", new[] { Tag.Parse("MER ") } }, // Meru
            { "mev", new[] { Tag.Parse("MEV ") } }, // Mano
            { "mfa", new[] { Tag.Parse("MFA ") } }, // Pattani Malay
            { "mfb", new[] { Tag.Parse("MLY ") } }, // Malay
            { "mfe", new[] { Tag.Parse("CPP "), Tag.Parse("MFE ") } }, // Creoles; Morisyen
            { "mfp", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "mga", new[] { Tag.Parse("SGA ") } }, // Old Irish
            { "mhc", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "mhr", new[] { Tag.Parse("LMA ") } }, // Low Mari
            { "mhv", new[] { Tag.Parse("ARK ") } }, // Rakhine
            { "min", new[] { Tag.Parse("MIN ") } }, // Minangkabau
            { "mkd", new[] { Tag.Parse("MKD ") } }, // Macedonian
            { "mkn", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "mku", new[] { Tag.Parse("MNK ") } }, // Maninka
            { "mkw", new[] { Tag.Parse("MKW ") } }, // Kituba
            { "mlg", new[] { Tag.Parse("MLG ") } }, // Malagasy
            { "mlq", new[] { Tag.Parse("MLN "), Tag.Parse("MNK ") } }, // Malinke; Maninka
            { "mlt", new[] { Tag.Parse("MTS ") } }, // Maltese
            { "mmr", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "mnc", new[] { Tag.Parse("MCH ") } }, // Manchu
            { "mnh", new[] { Tag.Parse("BAD0") } }, // Banda
            { "mni", new[] { Tag.Parse("MNI ") } }, // Manipuri
            { "mnk", new[] { Tag.Parse("MND "), Tag.Parse("MNK ") } }, // Mandinka; Maninka
            { "mns", new[] { Tag.Parse("MAN ") } }, // Mansi
            { "mnw", new[] { Tag.Parse("MON "), Tag.Parse("MONT") } }, // Mon; Thailand Mon
            { "mo", new[] { Tag.Parse("ROM ") } }, // Romanian
            { "mod", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "moh", new[] { Tag.Parse("MOH ") } }, // Mohawk
            { "mol", new[] { Tag.Parse("MOL ") } }, // Moldavian
            { "mon", new[] { Tag.Parse("MNG ") } }, // Mongolian
            { "mop", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "mos", new[] { Tag.Parse("MOS ") } }, // Mossi
            { "mpe", new[] { Tag.Parse("MAJ ") } }, // Majang
            { "mqg", new[] { Tag.Parse("MLY ") } }, // Malay
            { "mrh", new[] { Tag.Parse("QIN ") } }, // Chin
            { "mri", new[] { Tag.Parse("MRI ") } }, // Maori
            { "mrj", new[] { Tag.Parse("HMA ") } }, // High Mari
            { "msa", new[] { Tag.Parse("MLY ") } }, // Malay
            { "msc", new[] { Tag.Parse("MNK ") } }, // Maninka
            { "msh", new[] { Tag.Parse("MLG ") } }, // Malagasy
            { "msi", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "mtr", new[] { Tag.Parse("MAW ") } }, // Marwari
            { "mud", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "mui", new[] { Tag.Parse("MLY ") } }, // Malay
            { "mup", new[] { Tag.Parse("RAJ ") } }, // Rajasthani
            { "muq", new[] { Tag.Parse("HMN ") } }, // Hmong
            { "mus", new[] { Tag.Parse("MUS ") } }, // Muscogee
            { "mvb", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "mve", new[] { Tag.Parse("MAW ") } }, // Marwari
            { "mvf", new[] { Tag.Parse("MNG ") } }, // Mongolian
            { "mwk", new[] { Tag.Parse("MNK ") } }, // Maninka
            { "mwl", new[] { Tag.Parse("MWL ") } }, // Mirandese
            { "mwq", new[] { Tag.Parse("QIN ") } }, // Chin
            { "mwr", new[] { Tag.Parse("MAW ") } }, // Marwari
            { "mww", new[] { Tag.Parse("MWW ") } }, // Hmong Daw
            { "mya", new[] { Tag.Parse("BRM ") } }, // Burmese
            { "mym", new[] { Tag.Parse("MEN ") } }, // Me’en
            { "myn", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "myq", new[] { Tag.Parse("MNK ") } }, // Maninka
            { "myv", new[] { Tag.Parse("ERZ ") } }, // Erzya
            { "mzb", new[] { Tag.Parse("BBR ") } }, // Berber
            { "mzn", new[] { Tag.Parse("MZN ") } }, // Mazanderani
            { "mzs", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "nag", new[] { Tag.Parse("CPP "), Tag.Parse("NAG ") } }, // Creoles; Naga-Assamese
            { "nah", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nap", new[] { Tag.Parse("NAP ") } }, // Neapolitan
            { "nau", new[] { Tag.Parse("NAU ") } }, // Nauruan
            { "nav", new[] { Tag.Parse("ATH "), Tag.Parse("NAV ") } }, // Athapaskan languages; Navajo
            { "naz", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nbl", new[] { Tag.Parse("NDB ") } }, // Ndebele
            { "nch", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nci", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "ncj", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "ncl", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "ncx", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "ndc", new[] { Tag.Parse("NDC ") } }, // Ndau
            { "nde", new[] { Tag.Parse("NDB ") } }, // Ndebele
            { "ndo", new[] { Tag.Parse("NDG ") } }, // Ndonga
            { "nds", new[] { Tag.Parse("NDS ") } }, // Low Saxon
            { "nef", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "nep", new[] { Tag.Parse("NEP ") } }, // Nepali
            { "new", new[] { Tag.Parse("NEW ") } }, // Newari
            { "nga", new[] { Tag.Parse("NGA ") } }, // Ngbaka
            { "ngl", new[] { Tag.Parse("LMW ") } }, // Lomwe
            { "ngm", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "ngo", new[] { Tag.Parse("SXT ") } }, // Sutu
            { "ngu", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nhc", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nhd", new[] { Tag.Parse("GUA ") } }, // Guarani
            { "nhe", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nhg", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nhi", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nhk", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nhm", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nhn", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nhp", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nhq", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nht", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nhv", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nhw", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nhx", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nhy", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nhz", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "niq", new[] { Tag.Parse("KAL ") } }, // Kalenjin
            { "niu", new[] { Tag.Parse("NIU ") } }, // Niuean
            { "niv", new[] { Tag.Parse("GIL ") } }, // Gilyak
            { "njt", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "njz", new[] { Tag.Parse("NIS ") } }, // Nisi
            { "nkx", new[] { Tag.Parse("IJO ") } }, // Ijo languages
            { "nla", new[] { Tag.Parse("BML ") } }, // Bamileke
            { "nld", new[] { Tag.Parse("NLD ") } }, // Dutch
            { "nle", new[] { Tag.Parse("LUH ") } }, // Luyia
            { "nlv", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nnh", new[] { Tag.Parse("BML ") } }, // Bamileke
            { "nno", new[] { Tag.Parse("NYN ") } }, // Norwegian Nynorsk (Nynorsk, Norwegian)
            { "nnz", new[] { Tag.Parse("BML ") } }, // Bamileke
            { "nob", new[] { Tag.Parse("NOR ") } }, // Norwegian
            { "nod", new[] { Tag.Parse("NTA ") } }, // Northern Tai
            { "noe", new[] { Tag.Parse("NOE ") } }, // Nimadi
            { "nog", new[] { Tag.Parse("NOG ") } }, // Nogai
            { "nop", new[] { Tag.Parse("NOP ") } }, // Numanggang
            { "nov", new[] { Tag.Parse("NOV ") } }, // Novial
            { "npi", new[] { Tag.Parse("NEP ") } }, // Nepali
            { "npl", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nqo", new[] { Tag.Parse("NKO ") } }, // N’Ko
            { "nsk", new[] { Tag.Parse("NAS ") } }, // Naskapi
            { "nso", new[] { Tag.Parse("NSO ") } }, // Northern Sotho
            { "nsu", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nue", new[] { Tag.Parse("BAD0") } }, // Banda
            { "nuk", new[] { Tag.Parse("NUK ") } }, // Nuu-chah-nulth
            { "nuu", new[] { Tag.Parse("BAD0") } }, // Banda
            { "nuz", new[] { Tag.Parse("NAH ") } }, // Nahuatl
            { "nwe", new[] { Tag.Parse("BML ") } }, // Bamileke
            { "nya", new[] { Tag.Parse("CHI ") } }, // Chichewa (Chewa, Nyanja)
            { "nyd", new[] { Tag.Parse("LUH ") } }, // Luyia
            { "nym", new[] { Tag.Parse("NYM ") } }, // Nyamwezi
            { "nyn", new[] { Tag.Parse("NKL ") } }, // Nyankole
            { "nza", new[] { Tag.Parse("NZA ") } }, // Mbembe Tigon
            { "oci", new[] { Tag.Parse("OCI ") } }, // Occitan
            { "ojb", new[] { Tag.Parse("OJB ") } }, // Ojibway
            { "ojc", new[] { Tag.Parse("OJB ") } }, // Ojibway
            { "ojg", new[] { Tag.Parse("OJB ") } }, // Ojibway
            { "oji", new[] { Tag.Parse("OJB ") } }, // Ojibway
            { "ojs", new[] { Tag.Parse("OCR ") } }, // Oji-Cree
            { "ojw", new[] { Tag.Parse("OJB ") } }, // Ojibway
            { "okd", new[] { Tag.Parse("IJO ") } }, // Ijo languages
            { "oki", new[] { Tag.Parse("KAL ") } }, // Kalenjin
            { "okm", new[] { Tag.Parse("KOH ") } }, // Korean Old Hangul
            { "okr", new[] { Tag.Parse("IJO ") } }, // Ijo languages
            { "one", new[] { Tag.Parse("ONE ") } }, // Oneida
            { "ono", new[] { Tag.Parse("ONO ") } }, // Onondaga
            { "onx", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "oor", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "orc", new[] { Tag.Parse("ORO ") } }, // Oromo
            { "ori", new[] { Tag.Parse("ORI ") } }, // Odia
            { "orm", new[] { Tag.Parse("ORO ") } }, // Oromo
            { "orn", new[] { Tag.Parse("MLY ") } }, // Malay
            { "orr", new[] { Tag.Parse("IJO ") } }, // Ijo languages
            { "ors", new[] { Tag.Parse("MLY ") } }, // Malay
            { "ory", new[] { Tag.Parse("ORI ") } }, // Odia
            { "oss", new[] { Tag.Parse("OSS ") } }, // Ossetian
            { "otw", new[] { Tag.Parse("OJB ") } }, // Ojibway
            { "oua", new[] { Tag.Parse("BBR ") } }, // Berber
            { "pag", new[] { Tag.Parse("PAG ") } }, // Pangasinan
            { "pam", new[] { Tag.Parse("PAM ") } }, // Pampangan
            { "pan", new[] { Tag.Parse("PAN ") } }, // Punjabi
            { "pap", new[] { Tag.Parse("CPP "), Tag.Parse("PAP0") } }, // Creoles; Papiamentu
            { "pau", new[] { Tag.Parse("PAU ") } }, // Palauan
            { "pbt", new[] { Tag.Parse("PAS ") } }, // Pashto
            { "pbu", new[] { Tag.Parse("PAS ") } }, // Pashto
            { "pcc", new[] { Tag.Parse("PCC ") } }, // Bouyei
            { "pcd", new[] { Tag.Parse("PCD ") } }, // Picard
            { "pce", new[] { Tag.Parse("PLG ") } }, // Palaung
            { "pck", new[] { Tag.Parse("QIN ") } }, // Chin
            { "pcm", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "pdc", new[] { Tag.Parse("PDC ") } }, // Pennsylvania German
            { "pdu", new[] { Tag.Parse("KRN ") } }, // Karen
            { "pea", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "pel", new[] { Tag.Parse("MLY ") } }, // Malay
            { "pes", new[] { Tag.Parse("FAR ") } }, // Persian
            { "pey", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "pga", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "phk", new[] { Tag.Parse("PHK ") } }, // Phake
            { "pih", new[] { Tag.Parse("CPP "), Tag.Parse("PIH ") } }, // Creoles; Norfolk
            { "pis", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "pkh", new[] { Tag.Parse("QIN ") } }, // Chin
            { "pko", new[] { Tag.Parse("KAL ") } }, // Kalenjin
            { "plg", new[] { Tag.Parse("PLG0") } }, // Pilagá
            { "pli", new[] { Tag.Parse("PAL ") } }, // Pali
            { "pll", new[] { Tag.Parse("PLG ") } }, // Palaung
            { "pln", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "plp", new[] { Tag.Parse("PAP ") } }, // Palpa
            { "plt", new[] { Tag.Parse("MLG ") } }, // Malagasy
            { "pml", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "pms", new[] { Tag.Parse("PMS ") } }, // Piemontese
            { "pmy", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "pnb", new[] { Tag.Parse("PNB ") } }, // Western Panjabi
            { "poc", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "poh", new[] { Tag.Parse("MYN "), Tag.Parse("POH ") } }, // Mayan; Pocomchi
            { "pol", new[] { Tag.Parse("PLK ") } }, // Polish
            { "pon", new[] { Tag.Parse("PON ") } }, // Pohnpeian
            { "por", new[] { Tag.Parse("PTG ") } }, // Portuguese
            { "pov", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "ppa", new[] { Tag.Parse("BAG ") } }, // Baghelkhandi
            { "pre", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "pro", new[] { Tag.Parse("PRO ") } }, // Provençal / Old Provençal
            { "prp", new[] { Tag.Parse("GUJ ") } }, // Gujarati
            { "prs", new[] { Tag.Parse("DRI ") } }, // Dari
            { "pse", new[] { Tag.Parse("MLY ") } }, // Malay
            { "pst", new[] { Tag.Parse("PAS ") } }, // Pashto
            { "pub", new[] { Tag.Parse("QIN ") } }, // Chin
            { "pus", new[] { Tag.Parse("PAS ") } }, // Pashto
            { "puz", new[] { Tag.Parse("QIN ") } }, // Chin
            { "pwo", new[] { Tag.Parse("KRN "), Tag.Parse("PWO ") } }, // Karen; Western Pwo Karen
            { "pww", new[] { Tag.Parse("KRN ") } }, // Karen
            { "quc", new[] { Tag.Parse("MYN "), Tag.Parse("QUC ") } }, // Mayan; K’iche’
            { "quh", new[] { Tag.Parse("QUH ") } }, // Quechua (Bolivia)
            { "qum", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "quv", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "quz", new[] { Tag.Parse("QUZ ") } }, // Quechua
            { "qvi", new[] { Tag.Parse("QVI ") } }, // Quechua (Ecuador)
            { "qwh", new[] { Tag.Parse("QWH ") } }, // Quechua (Peru)
            { "qwt", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "rag", new[] { Tag.Parse("LUH ") } }, // Luyia
            { "raj", new[] { Tag.Parse("RAJ ") } }, // Rajasthani
            { "ral", new[] { Tag.Parse("QIN ") } }, // Chin
            { "rar", new[] { Tag.Parse("RAR ") } }, // Rarotongan
            { "rbb", new[] { Tag.Parse("PLG ") } }, // Palaung
            { "rbl", new[] { Tag.Parse("BIK ") } }, // Bikol
            { "rcf", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "rej", new[] { Tag.Parse("REJ ") } }, // Rejang
            { "rhg", new[] { Tag.Parse("RHG ") } }, // Rohingya
            { "ria", new[] { Tag.Parse("RIA ") } }, // Riang
            { "rif", new[] { Tag.Parse("BBR "), Tag.Parse("RIF ") } }, // Berber; Tarifit
            { "rit", new[] { Tag.Parse("RIT ") } }, // Ritarungo
            { "rki", new[] { Tag.Parse("ARK ") } }, // Rakhine
            { "rkw", new[] { Tag.Parse("RKW ") } }, // Arakwal
            { "rmc", new[] { Tag.Parse("ROY ") } }, // Romany
            { "rmf", new[] { Tag.Parse("ROY ") } }, // Romany
            { "rml", new[] { Tag.Parse("ROY ") } }, // Romany
            { "rmn", new[] { Tag.Parse("ROY ") } }, // Romany
            { "rmo", new[] { Tag.Parse("ROY ") } }, // Romany
            { "rmw", new[] { Tag.Parse("ROY ") } }, // Romany
            { "rmy", new[] { Tag.Parse("RMY ") } }, // Vlax Romani
            { "rmz", new[] { Tag.Parse("ARK ") } }, // Rakhine
            { "roh", new[] { Tag.Parse("RMS ") } }, // Romansh
            { "rom", new[] { Tag.Parse("ROY ") } }, // Romany
            { "ron", new[] { Tag.Parse("ROM ") } }, // Romanian
            { "rop", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "rtc", new[] { Tag.Parse("QIN ") } }, // Chin
            { "rtm", new[] { Tag.Parse("RTM ") } }, // Rotuman
            { "rue", new[] { Tag.Parse("RSY ") } }, // Rusyn
            { "run", new[] { Tag.Parse("RUN ") } }, // Rundi
            { "rup", new[] { Tag.Parse("RUP ") } }, // Aromanian
            { "rus", new[] { Tag.Parse("RUS ") } }, // Russian
            { "rwr", new[] { Tag.Parse("MAW ") } }, // Marwari
            { "sag", new[] { Tag.Parse("SGO ") } }, // Sango
            { "sah", new[] { Tag.Parse("YAK ") } }, // Sakha
            { "sam", new[] { Tag.Parse("PAA ") } }, // Palestinian Aramaic
            { "san", new[] { Tag.Parse("SAN ") } }, // Sanskrit
            { "sas", new[] { Tag.Parse("SAS ") } }, // Sasak
            { "sat", new[] { Tag.Parse("SAT ") } }, // Santali
            { "scf", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "sch", new[] { Tag.Parse("QIN ") } }, // Chin
            { "sci", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "sck", new[] { Tag.Parse("SAD ") } }, // Sadri
            { "scn", new[] { Tag.Parse("SCN ") } }, // Sicilian
            { "sco", new[] { Tag.Parse("SCO ") } }, // Scots
            { "scs", new[] { Tag.Parse("ATH "), Tag.Parse("SCS "), Tag.Parse("SLA ") } }, // Athapaskan languages; North Slavey; Slavey
            { "sdc", new[] { Tag.Parse("SRD ") } }, // Sardinian
            { "sdh", new[] { Tag.Parse("KUR ") } }, // Kurdish
            { "sdn", new[] { Tag.Parse("SRD ") } }, // Sardinian
            { "sds", new[] { Tag.Parse("BBR ") } }, // Berber
            { "see", new[] { Tag.Parse("SEE ") } }, // Seneca
            { "seh", new[] { Tag.Parse("SNA ") } }, // Sena
            { "sek", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "sel", new[] { Tag.Parse("SEL ") } }, // Selkup
            { "sez", new[] { Tag.Parse("QIN ") } }, // Chin
            { "sfm", new[] { Tag.Parse("SFM ") } }, // Small Flowery Miao
            { "sga", new[] { Tag.Parse("SGA ") } }, // Old Irish
            { "sgc", new[] { Tag.Parse("KAL ") } }, // Kalenjin
            { "sgs", new[] { Tag.Parse("SGS ") } }, // Samogitian
            { "sgw", new[] { Tag.Parse("CHG ") } }, // Chaha Gurage
            { "shi", new[] { Tag.Parse("BBR "), Tag.Parse("SHI ") } }, // Berber; Tachelhit
            { "shl", new[] { Tag.Parse("QIN ") } }, // Chin
            { "shn", new[] { Tag.Parse("SHN ") } }, // Shan
            { "shu", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "shy", new[] { Tag.Parse("BBR ") } }, // Berber
            { "sid", new[] { Tag.Parse("SID ") } }, // Sidamo
            { "sin", new[] { Tag.Parse("SNH ") } }, // Sinhala (Sinhalese)
            { "siz", new[] { Tag.Parse("BBR ") } }, // Berber
            { "sja", new[] { Tag.Parse("SJA ") } }, // Epena
            { "sjd", new[] { Tag.Parse("KSM ") } }, // Kildin Sami
            { "sje", new[] { Tag.Parse("SJE ") } }, // Pite Sami
            { "sjo", new[] { Tag.Parse("SIB ") } }, // Sibe
            { "sjs", new[] { Tag.Parse("BBR ") } }, // Berber
            { "sju", new[] { Tag.Parse("SJU ") } }, // Ume Sami
            { "skg", new[] { Tag.Parse("MLG ") } }, // Malagasy
            { "skr", new[] { Tag.Parse("SRK ") } }, // Saraiki
            { "skw", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "slk", new[] { Tag.Parse("SKY ") } }, // Slovak
            { "slv", new[] { Tag.Parse("SLV ") } }, // Slovenian
            { "sma", new[] { Tag.Parse("SSM ") } }, // Southern Sami
            { "smd", new[] { Tag.Parse("MBN ") } }, // Mbundu
            { "sme", new[] { Tag.Parse("NSM ") } }, // Northern Sami
            { "smj", new[] { Tag.Parse("LSM ") } }, // Lule Sami
            { "smn", new[] { Tag.Parse("ISM ") } }, // Inari Sami
            { "smo", new[] { Tag.Parse("SMO ") } }, // Samoan
            { "sms", new[] { Tag.Parse("SKS ") } }, // Skolt Sami
            { "smt", new[] { Tag.Parse("QIN ") } }, // Chin
            { "sna", new[] { Tag.Parse("SNA0") } }, // Shona
            { "snb", new[] { Tag.Parse("IBA ") } }, // Iban
            { "snd", new[] { Tag.Parse("SND ") } }, // Sindhi
            { "snk", new[] { Tag.Parse("SNK ") } }, // Soninke
            { "som", new[] { Tag.Parse("SML ") } }, // Somali
            { "sop", new[] { Tag.Parse("SOP ") } }, // Songe
            { "sot", new[] { Tag.Parse("SOT ") } }, // Southern Sotho
            { "spa", new[] { Tag.Parse("ESP ") } }, // Spanish
            { "spv", new[] { Tag.Parse("ORI ") } }, // Odia
            { "spy", new[] { Tag.Parse("KAL ") } }, // Kalenjin
            { "sqi", new[] { Tag.Parse("SQI ") } }, // Albanian
            { "sr", new[] { Tag.Parse("SRB ") } }, // Serbian
            { "src", new[] { Tag.Parse("SRD ") } }, // Sardinian
            { "srd", new[] { Tag.Parse("SRD ") } }, // Sardinian
            { "srm", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "srn", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "sro", new[] { Tag.Parse("SRD ") } }, // Sardinian
            { "srp", new[] { Tag.Parse("SRB ") } }, // Serbian
            { "srr", new[] { Tag.Parse("SRR ") } }, // Serer
            { "srs", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "ssh", new[] { Tag.Parse("ARA ") } }, // Arabic
            { "ssw", new[] { Tag.Parse("SWZ ") } }, // Swati
            { "sta", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "stq", new[] { Tag.Parse("STQ ") } }, // Saterland Frisian
            { "str", new[] { Tag.Parse("STR ") } }, // Straits Salish
            { "stv", new[] { Tag.Parse("SIG ") } }, // Silte Gurage
            { "suk", new[] { Tag.Parse("SUK ") } }, // Sukuma
            { "sun", new[] { Tag.Parse("SUN ") } }, // Sundanese
            { "suq", new[] { Tag.Parse("SUR ") } }, // Suri
            { "sva", new[] { Tag.Parse("SVA ") } }, // Svan
            { "svc", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "swa", new[] { Tag.Parse("SWK ") } }, // Swahili
            { "swb", new[] { Tag.Parse("CMR ") } }, // Comorian
            { "swc", new[] { Tag.Parse("SWK ") } }, // Swahili
            { "swe", new[] { Tag.Parse("SVE ") } }, // Swedish
            { "swh", new[] { Tag.Parse("SWK ") } }, // Swahili
            { "swn", new[] { Tag.Parse("BBR ") } }, // Berber
            { "swv", new[] { Tag.Parse("MAW ") } }, // Marwari
            { "sxu", new[] { Tag.Parse("SXU ") } }, // Upper Saxon
            { "syc", new[] { Tag.Parse("SYR "), Tag.Parse("SYRE"), Tag.Parse("SYRJ"), Tag.Parse("SYRN") } }, // Syriac; Syriac, Estrangela script-variant (equivalent to ISO 15924 'Syre'); Syriac, Western script-variant (equivalent to ISO 15924 'Syrj'); Syriac, Eastern script-variant (equivalent to ISO 15924 'Syrn')
            { "syl", new[] { Tag.Parse("SYL ") } }, // Sylheti
            { "syr", new[] { Tag.Parse("SYR "), Tag.Parse("SYRE"), Tag.Parse("SYRJ"), Tag.Parse("SYRN") } }, // Syriac; Syriac, Estrangela script-variant (equivalent to ISO 15924 'Syre'); Syriac, Western script-variant (equivalent to ISO 15924 'Syrj'); Syriac, Eastern script-variant (equivalent to ISO 15924 'Syrn')
            { "szl", new[] { Tag.Parse("SZL ") } }, // Silesian
            { "taa", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "tab", new[] { Tag.Parse("TAB ") } }, // Tabasaran
            { "tah", new[] { Tag.Parse("THT ") } }, // Tahitian
            { "tam", new[] { Tag.Parse("TAM ") } }, // Tamil
            { "taq", new[] { Tag.Parse("BBR "), Tag.Parse("TAQ "), Tag.Parse("TMH ") } }, // Berber; Tamasheq; Tamashek
            { "tas", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "tat", new[] { Tag.Parse("TAT ") } }, // Tatar
            { "tau", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "tbv", new[] { Tag.Parse("TBV ") } }, // Tobo
            { "tcb", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "tce", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "tch", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "tcp", new[] { Tag.Parse("QIN ") } }, // Chin
            { "tcs", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "tcy", new[] { Tag.Parse("TUL ") } }, // Tulu
            { "tcz", new[] { Tag.Parse("QIN ") } }, // Chin
            { "tdc", new[] { Tag.Parse("TDC ") } }, // Emberá-Tadó
            { "tdd", new[] { Tag.Parse("TDD ") } }, // Dehong Dai
            { "tdx", new[] { Tag.Parse("MLG ") } }, // Malagasy
            { "tec", new[] { Tag.Parse("KAL ") } }, // Kalenjin
            { "tel", new[] { Tag.Parse("TEL ") } }, // Telugu
            { "tem", new[] { Tag.Parse("TMN ") } }, // Temne
            { "tet", new[] { Tag.Parse("TET ") } }, // Tetum
            { "tez", new[] { Tag.Parse("BBR ") } }, // Berber
            { "tfn", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "tgh", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "tgj", new[] { Tag.Parse("NIS ") } }, // Nisi
            { "tgk", new[] { Tag.Parse("TAJ ") } }, // Tajiki
            { "tgl", new[] { Tag.Parse("TGL ") } }, // Tagalog
            { "tgx", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "tha", new[] { Tag.Parse("THA ") } }, // Thai
            { "thp", new[] { Tag.Parse("THP ") } }, // Thompson
            { "tht", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "thv", new[] { Tag.Parse("BBR "), Tag.Parse("THV "), Tag.Parse("TMH ") } }, // Berber; Tahaggart Tamahaq; Tamashek
            { "thz", new[] { Tag.Parse("BBR "), Tag.Parse("THZ "), Tag.Parse("TMH ") } }, // Berber; Tayart Tamajeq; Tamashek
            { "tia", new[] { Tag.Parse("BBR ") } }, // Berber
            { "tig", new[] { Tag.Parse("TGR ") } }, // Tigre
            { "tir", new[] { Tag.Parse("TGY ") } }, // Tigrinya
            { "tiv", new[] { Tag.Parse("TIV ") } }, // Tiv
            { "tjl", new[] { Tag.Parse("TJL ") } }, // Tai Laing
            { "tjo", new[] { Tag.Parse("BBR ") } }, // Berber
            { "tkg", new[] { Tag.Parse("MLG ") } }, // Malagasy
            { "tli", new[] { Tag.Parse("TLI ") } }, // Tlingit
            { "tly", new[] { Tag.Parse("TLY ") } }, // Talysh
            { "tmg", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "tmh", new[] { Tag.Parse("BBR "), Tag.Parse("TMH ") } }, // Berber; Tamashek
            { "tmw", new[] { Tag.Parse("MLY ") } }, // Malay
            { "tnf", new[] { Tag.Parse("DRI ") } }, // Dari
            { "tod", new[] { Tag.Parse("TOD0") } }, // Toma
            { "toi", new[] { Tag.Parse("TNG ") } }, // Tonga
            { "toj", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "tol", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "ton", new[] { Tag.Parse("TGN ") } }, // Tongan
            { "tor", new[] { Tag.Parse("BAD0") } }, // Banda
            { "tpi", new[] { Tag.Parse("CPP "), Tag.Parse("TPI ") } }, // Creoles; Tok Pisin
            { "trf", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "tru", new[] { Tag.Parse("SYR "), Tag.Parse("TUA ") } }, // Syriac; Turoyo Aramaic
            { "tsj", new[] { Tag.Parse("TSJ ") } }, // Tshangla
            { "tsn", new[] { Tag.Parse("TNA ") } }, // Tswana
            { "tso", new[] { Tag.Parse("TSG ") } }, // Tsonga
            { "ttc", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "ttm", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "ttq", new[] { Tag.Parse("BBR "), Tag.Parse("TMH "), Tag.Parse("TTQ ") } }, // Berber; Tamashek; Tawallammat Tamajaq
            { "tuk", new[] { Tag.Parse("TKM ") } }, // Turkmen
            { "tum", new[] { Tag.Parse("TUM ") } }, // Tumbuka
            { "tur", new[] { Tag.Parse("TRK ") } }, // Turkish
            { "tus", new[] { Tag.Parse("TUS ") } }, // Tuscarora
            { "tuu", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "tuy", new[] { Tag.Parse("KAL ") } }, // Kalenjin
            { "tvl", new[] { Tag.Parse("TVL ") } }, // Tuvalu
            { "tvy", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "tw", new[] { Tag.Parse("AKA ") } }, // Akan
            { "twi", new[] { Tag.Parse("AKA "), Tag.Parse("TWI ") } }, // Akan; Twi
            { "txc", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "txy", new[] { Tag.Parse("MLG ") } }, // Malagasy
            { "tyv", new[] { Tag.Parse("TUV ") } }, // Tuvin
            { "tyz", new[] { Tag.Parse("TYZ ") } }, // Tày
            { "tzh", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "tzj", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "tzm", new[] { Tag.Parse("BBR "), Tag.Parse("TZM ") } }, // Berber; Tamazight
            { "tzo", new[] { Tag.Parse("MYN "), Tag.Parse("TZO ") } }, // Mayan; Tzotzil
            { "ubl", new[] { Tag.Parse("BIK ") } }, // Bikol
            { "udi", new[] { Tag.Parse("UDI ") } }, // Udi
            { "udm", new[] { Tag.Parse("UDM ") } }, // Udmurt
            { "uig", new[] { Tag.Parse("UYG ") } }, // Uyghur
            { "ukr", new[] { Tag.Parse("UKR ") } }, // Ukrainian
            { "uln", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "umb", new[] { Tag.Parse("UMB ") } }, // Umbundu
            { "unr", new[] { Tag.Parse("MUN ") } }, // Mundari
            { "urd", new[] { Tag.Parse("URD ") } }, // Urdu
            { "urk", new[] { Tag.Parse("MLY ") } }, // Malay
            { "usp", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "uzb", new[] { Tag.Parse("UZB ") } }, // Uzbek
            { "uzn", new[] { Tag.Parse("UZB ") } }, // Uzbek
            { "uzs", new[] { Tag.Parse("UZB ") } }, // Uzbek
            { "vap", new[] { Tag.Parse("QIN ") } }, // Chin
            { "vec", new[] { Tag.Parse("VEC ") } }, // Venetian
            { "ven", new[] { Tag.Parse("VEN ") } }, // Venda
            { "vic", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "vie", new[] { Tag.Parse("VIT ") } }, // Vietnamese
            { "vkk", new[] { Tag.Parse("MLY ") } }, // Malay
            { "vkp", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "vkt", new[] { Tag.Parse("MLY ") } }, // Malay
            { "vls", new[] { Tag.Parse("FLE ") } }, // Dutch (Flemish)
            { "vmw", new[] { Tag.Parse("MAK ") } }, // Makhuwa
            { "vol", new[] { Tag.Parse("VOL ") } }, // Volapük
            { "vro", new[] { Tag.Parse("VRO ") } }, // Võro
            { "vsn", new[] { Tag.Parse("SAN ") } }, // Sanskrit
            { "war", new[] { Tag.Parse("WAR ") } }, // Waray-Waray
            { "wbl", new[] { Tag.Parse("WBL ") } }, // Wakhi
            { "wbm", new[] { Tag.Parse("WA  ") } }, // Wa
            { "wbr", new[] { Tag.Parse("WAG ") } }, // Wagdi
            { "wci", new[] { Tag.Parse("WCI ") } }, // Waci Gbe
            { "wdt", new[] { Tag.Parse("WDT ") } }, // Wendat
            { "wea", new[] { Tag.Parse("KRN ") } }, // Karen
            { "wes", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "weu", new[] { Tag.Parse("QIN ") } }, // Chin
            { "wlc", new[] { Tag.Parse("CMR ") } }, // Comorian
            { "wle", new[] { Tag.Parse("SIG ") } }, // Silte Gurage
            { "wlk", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "wln", new[] { Tag.Parse("WLN ") } }, // Walloon
            { "wni", new[] { Tag.Parse("CMR ") } }, // Comorian
            { "wol", new[] { Tag.Parse("WLF ") } }, // Wolof
            { "wry", new[] { Tag.Parse("MAW ") } }, // Marwari
            { "wsg", new[] { Tag.Parse("GON ") } }, // Gondi
            { "wtm", new[] { Tag.Parse("WTM ") } }, // Mewati
            { "wyn", new[] { Tag.Parse("WYN ") } }, // Wyandot
            { "xal", new[] { Tag.Parse("KLM "), Tag.Parse("TOD ") } }, // Kalmyk; Todo
            { "xan", new[] { Tag.Parse("SEK ") } }, // Sekota
            { "xho", new[] { Tag.Parse("XHS ") } }, // Xhosa
            { "xjb", new[] { Tag.Parse("XJB ") } }, // Minjangbal
            { "xkf", new[] { Tag.Parse("XKF ") } }, // Khengkha
            { "xmg", new[] { Tag.Parse("BML ") } }, // Bamileke
            { "xmm", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "xmv", new[] { Tag.Parse("MLG ") } }, // Malagasy
            { "xmw", new[] { Tag.Parse("MLG ") } }, // Malagasy
            { "xnj", new[] { Tag.Parse("SXT ") } }, // Sutu
            { "xnq", new[] { Tag.Parse("SXT ") } }, // Sutu
            { "xnr", new[] { Tag.Parse("DGR ") } }, // Dogri (macrolanguage)
            { "xog", new[] { Tag.Parse("XOG ") } }, // Soga
            { "xpe", new[] { Tag.Parse("XPE ") } }, // Kpelle (Liberia)
            { "xsl", new[] { Tag.Parse("ATH "), Tag.Parse("SLA "), Tag.Parse("SSL ") } }, // Athapaskan languages; Slavey; South Slavey
            { "xst", new[] { Tag.Parse("SIG ") } }, // Silte Gurage
            { "xub", new[] { Tag.Parse("XUB ") } }, // Bette Kuruma
            { "xuj", new[] { Tag.Parse("XUJ ") } }, // Jennu Kuruma
            { "xup", new[] { Tag.Parse("ATH ") } }, // Athapaskan languages
            { "yaj", new[] { Tag.Parse("BAD0") } }, // Banda
            { "yao", new[] { Tag.Parse("YAO ") } }, // Yao
            { "yap", new[] { Tag.Parse("YAP ") } }, // Yapese
            { "ybb", new[] { Tag.Parse("BML ") } }, // Bamileke
            { "ybd", new[] { Tag.Parse("ARK ") } }, // Rakhine
            { "ycr", new[] { Tag.Parse("CPP ") } }, // Creoles
            { "ydd", new[] { Tag.Parse("JII ") } }, // Yiddish
            { "ygp", new[] { Tag.Parse("YGP ") } }, // Gepo
            { "yid", new[] { Tag.Parse("JII ") } }, // Yiddish
            { "yih", new[] { Tag.Parse("JII ") } }, // Yiddish
            { "yna", new[] { Tag.Parse("YNA ") } }, // Aluo
            { "yor", new[] { Tag.Parse("YBA ") } }, // Yoruba
            { "yos", new[] { Tag.Parse("QIN ") } }, // Chin
            { "yua", new[] { Tag.Parse("MYN ") } }, // Mayan
            { "yuf", new[] { Tag.Parse("YUF ") } }, // Havasupai-Walapai-Yavapai
            { "ywq", new[] { Tag.Parse("YWQ ") } }, // Wuding-Luquan Yi
            { "zch", new[] { Tag.Parse("ZHA ") } }, // Zhuang
            { "zdj", new[] { Tag.Parse("CMR ") } }, // Comorian
            { "zea", new[] { Tag.Parse("ZEA ") } }, // Zealandic
            { "zeh", new[] { Tag.Parse("ZHA ") } }, // Zhuang
            { "zen", new[] { Tag.Parse("BBR ") } }, // Berber
            { "zgb", new[] { Tag.Parse("ZHA ") } }, // Zhuang
            { "zgh", new[] { Tag.Parse("BBR "), Tag.Parse("ZGH ") } }, // Berber; Standard Moroccan Tamazight
            { "zgm", new[] { Tag.Parse("ZHA ") } }, // Zhuang
            { "zgn", new[] { Tag.Parse("ZHA ") } }, // Zhuang
            { "zha", new[] { Tag.Parse("ZHA ") } }, // Zhuang
            { "zhd", new[] { Tag.Parse("ZHA ") } }, // Zhuang
            { "zhn", new[] { Tag.Parse("ZHA ") } }, // Zhuang
            { "zho", new[] { Tag.Parse("ZHH "), Tag.Parse("ZHP "), Tag.Parse("ZHS "), Tag.Parse("ZHT "), Tag.Parse("ZHTM") } }, // Chinese, Traditional, Hong Kong SAR; Chinese, Phonetic; Chinese, Simplified; Chinese, Traditional; Chinese, Traditional, Macao SAR
            { "zkb", new[] { Tag.Parse("KHA ") } }, // Khakass
            { "zlj", new[] { Tag.Parse("ZHA ") } }, // Zhuang
            { "zlm", new[] { Tag.Parse("MLY ") } }, // Malay
            { "zln", new[] { Tag.Parse("ZHA ") } }, // Zhuang
            { "zlq", new[] { Tag.Parse("ZHA ") } }, // Zhuang
            { "zmi", new[] { Tag.Parse("MLY ") } }, // Malay
            { "zmz", new[] { Tag.Parse("BAD0") } }, // Banda
            { "zne", new[] { Tag.Parse("ZND ") } }, // Zande
            { "zom", new[] { Tag.Parse("QIN ") } }, // Chin
            { "zqe", new[] { Tag.Parse("ZHA ") } }, // Zhuang
            { "zsm", new[] { Tag.Parse("MLY ") } }, // Malay
            { "zul", new[] { Tag.Parse("ZUL ") } }, // Zulu
            { "zum", new[] { Tag.Parse("LRC ") } }, // Luri
            { "zyb", new[] { Tag.Parse("ZHA ") } }, // Zhuang
            { "zyg", new[] { Tag.Parse("ZHA ") } }, // Zhuang
            { "zyj", new[] { Tag.Parse("ZHA ") } }, // Zhuang
            { "zyn", new[] { Tag.Parse("ZHA ") } }, // Zhuang
            { "zyp", new[] { Tag.Parse("QIN ") } }, // Chin
            { "zza", new[] { Tag.Parse("ZZA ") } }, // Zazaki
            { "zzj", new[] { Tag.Parse("ZHA ") } }, // Zhuang
        };
}
