// Copyright (c) Six Labors.
// Licensed under the Apache License, Version 2.0.

using System;
using System.Collections.Generic;
using SixLabors.Fonts.Unicode;

namespace SixLabors.Fonts.Tables.AdvancedTypographic
{
    /// <summary>
    /// Provides a map from Unicode <see cref="Script"/> to OTF <see cref="Tag"/>.
    /// <see href="https://docs.microsoft.com/en-us/typography/opentype/spec/scripttags"/>
    /// </summary>
    internal sealed class UnicodeScriptTagMap : Dictionary<Script, Tag[]>
    {
        private static readonly Lazy<UnicodeScriptTagMap> Lazy = new Lazy<UnicodeScriptTagMap>(() => CreateMap());

        private UnicodeScriptTagMap()
        {
        }

        public static UnicodeScriptTagMap Instance => Lazy.Value;

        // TODO: This map will likely require updating to add aliases for old fonts.
        // Use HarfBuzz as a reference.
        private static UnicodeScriptTagMap CreateMap()
            => new UnicodeScriptTagMap
            {
              { Script.Unknown, new[] { Tag.Parse("zzzz") } },
              { Script.Common, new[] { Tag.Parse("zyyy") } },
              { Script.Inherited, new[] { Tag.Parse("zinh") } },
              { Script.Adlam, new[] { Tag.Parse("adlm") } },
              { Script.CaucasianAlbanian, new[] { Tag.Parse("aghb") } },
              { Script.Ahom, new[] { Tag.Parse("ahom") } },
              { Script.Arabic, new[] { Tag.Parse("arab") } },
              { Script.ImperialAramaic, new[] { Tag.Parse("armi") } },
              { Script.Armenian, new[] { Tag.Parse("armn") } },
              { Script.Avestan, new[] { Tag.Parse("avst") } },
              { Script.Balinese, new[] { Tag.Parse("bali") } },
              { Script.Bamum, new[] { Tag.Parse("bamu") } },
              { Script.BassaVah, new[] { Tag.Parse("bass") } },
              { Script.Batak, new[] { Tag.Parse("batk") } },
              { Script.Bengali, new[] { Tag.Parse("beng") } },
              { Script.Bhaiksuki, new[] { Tag.Parse("bhks") } },
              { Script.Bopomofo, new[] { Tag.Parse("bopo") } },
              { Script.Brahmi, new[] { Tag.Parse("brah") } },
              { Script.Braille, new[] { Tag.Parse("brai") } },
              { Script.Buginese, new[] { Tag.Parse("bugi") } },
              { Script.Buhid, new[] { Tag.Parse("buhd") } },
              { Script.Chakma, new[] { Tag.Parse("cakm") } },
              { Script.CanadianAboriginal, new[] { Tag.Parse("cans") } },
              { Script.Carian, new[] { Tag.Parse("cari") } },
              { Script.Cham, new[] { Tag.Parse("cham") } },
              { Script.Cherokee, new[] { Tag.Parse("cher") } },
              { Script.Chorasmian, new[] { Tag.Parse("chrs") } },
              { Script.Coptic, new[] { Tag.Parse("copt") } },
              { Script.Cypriot, new[] { Tag.Parse("cprt") } },
              { Script.Cyrillic, new[] { Tag.Parse("cyrl") } },
              { Script.Devanagari, new[] { Tag.Parse("deva") } },
              { Script.DivesAkuru, new[] { Tag.Parse("diak") } },
              { Script.Dogra, new[] { Tag.Parse("dogr") } },
              { Script.Deseret, new[] { Tag.Parse("dsrt") } },
              { Script.Duployan, new[] { Tag.Parse("dupl") } },
              { Script.EgyptianHieroglyphs, new[] { Tag.Parse("egyp") } },
              { Script.Elbasan, new[] { Tag.Parse("elba") } },
              { Script.Elymaic, new[] { Tag.Parse("elym") } },
              { Script.Ethiopic, new[] { Tag.Parse("ethi") } },
              { Script.Georgian, new[] { Tag.Parse("geor") } },
              { Script.Glagolitic, new[] { Tag.Parse("glag") } },
              { Script.GunjalaGondi, new[] { Tag.Parse("gong") } },
              { Script.MasaramGondi, new[] { Tag.Parse("gonm") } },
              { Script.Gothic, new[] { Tag.Parse("goth") } },
              { Script.Grantha, new[] { Tag.Parse("gran") } },
              { Script.Greek, new[] { Tag.Parse("grek") } },
              { Script.Gujarati, new[] { Tag.Parse("gujr") } },
              { Script.Gurmukhi, new[] { Tag.Parse("guru") } },
              { Script.Hangul, new[] { Tag.Parse("hang") } },
              { Script.Han, new[] { Tag.Parse("hani") } },
              { Script.Hanunoo, new[] { Tag.Parse("hano") } },
              { Script.Hatran, new[] { Tag.Parse("hatr") } },
              { Script.Hebrew, new[] { Tag.Parse("hebr") } },
              { Script.Hiragana, new[] { Tag.Parse("hira") } },
              { Script.AnatolianHieroglyphs, new[] { Tag.Parse("hluw") } },
              { Script.PahawhHmong, new[] { Tag.Parse("hmng") } },
              { Script.NyiakengPuachueHmong, new[] { Tag.Parse("hmnp") } },
              { Script.KatakanaOrHiragana, new[] { Tag.Parse("hrkt") } },
              { Script.OldHungarian, new[] { Tag.Parse("hung") } },
              { Script.OldItalic, new[] { Tag.Parse("ital") } },
              { Script.Javanese, new[] { Tag.Parse("java") } },
              { Script.KayahLi, new[] { Tag.Parse("kali") } },
              { Script.Katakana, new[] { Tag.Parse("kana") } },
              { Script.Kharoshthi, new[] { Tag.Parse("khar") } },
              { Script.Khmer, new[] { Tag.Parse("khmr") } },
              { Script.Khojki, new[] { Tag.Parse("khoj") } },
              { Script.KhitanSmallScript, new[] { Tag.Parse("kits") } },
              { Script.Kannada, new[] { Tag.Parse("knda") } },
              { Script.Kaithi, new[] { Tag.Parse("kthi") } },
              { Script.TaiTham, new[] { Tag.Parse("lana") } },
              { Script.Lao, new[] { Tag.Parse("laoo") } },
              { Script.Latin, new[] { Tag.Parse("latn") } },
              { Script.Lepcha, new[] { Tag.Parse("lepc") } },
              { Script.Limbu, new[] { Tag.Parse("limb") } },
              { Script.LinearA, new[] { Tag.Parse("lina") } },
              { Script.LinearB, new[] { Tag.Parse("linb") } },
              { Script.Lisu, new[] { Tag.Parse("lisu") } },
              { Script.Lycian, new[] { Tag.Parse("lyci") } },
              { Script.Lydian, new[] { Tag.Parse("lydi") } },
              { Script.Mahajani, new[] { Tag.Parse("mahj") } },
              { Script.Makasar, new[] { Tag.Parse("maka") } },
              { Script.Mandaic, new[] { Tag.Parse("mand") } },
              { Script.Manichaean, new[] { Tag.Parse("mani") } },
              { Script.Marchen, new[] { Tag.Parse("marc") } },
              { Script.Medefaidrin, new[] { Tag.Parse("medf") } },
              { Script.MendeKikakui, new[] { Tag.Parse("mend") } },
              { Script.MeroiticCursive, new[] { Tag.Parse("merc") } },
              { Script.MeroiticHieroglyphs, new[] { Tag.Parse("mero") } },
              { Script.Malayalam, new[] { Tag.Parse("mlym") } },
              { Script.Modi, new[] { Tag.Parse("modi") } },
              { Script.Mongolian, new[] { Tag.Parse("mong") } },
              { Script.Mro, new[] { Tag.Parse("mroo") } },
              { Script.MeeteiMayek, new[] { Tag.Parse("mtei") } },
              { Script.Multani, new[] { Tag.Parse("mult") } },
              { Script.Myanmar, new[] { Tag.Parse("mymr") } },
              { Script.Nandinagari, new[] { Tag.Parse("nand") } },
              { Script.OldNorthArabian, new[] { Tag.Parse("narb") } },
              { Script.Nabataean, new[] { Tag.Parse("nbat") } },
              { Script.Newa, new[] { Tag.Parse("newa") } },
              { Script.Nko, new[] { Tag.Parse("nkoo") } },
              { Script.Nushu, new[] { Tag.Parse("nshu") } },
              { Script.Ogham, new[] { Tag.Parse("ogam") } },
              { Script.OlChiki, new[] { Tag.Parse("olck") } },
              { Script.OldTurkic, new[] { Tag.Parse("orkh") } },
              { Script.Oriya, new[] { Tag.Parse("orya") } },
              { Script.Osage, new[] { Tag.Parse("osge") } },
              { Script.Osmanya, new[] { Tag.Parse("osma") } },
              { Script.Palmyrene, new[] { Tag.Parse("palm") } },
              { Script.PauCinHau, new[] { Tag.Parse("pauc") } },
              { Script.OldPermic, new[] { Tag.Parse("perm") } },
              { Script.PhagsPa, new[] { Tag.Parse("phag") } },
              { Script.InscriptionalPahlavi, new[] { Tag.Parse("phli") } },
              { Script.PsalterPahlavi, new[] { Tag.Parse("phlp") } },
              { Script.Phoenician, new[] { Tag.Parse("phnx") } },
              { Script.Miao, new[] { Tag.Parse("plrd") } },
              { Script.InscriptionalParthian, new[] { Tag.Parse("prti") } },
              { Script.Rejang, new[] { Tag.Parse("rjng") } },
              { Script.HanifiRohingya, new[] { Tag.Parse("rohg") } },
              { Script.Runic, new[] { Tag.Parse("runr") } },
              { Script.Samaritan, new[] { Tag.Parse("samr") } },
              { Script.OldSouthArabian, new[] { Tag.Parse("sarb") } },
              { Script.Saurashtra, new[] { Tag.Parse("saur") } },
              { Script.SignWriting, new[] { Tag.Parse("sgnw") } },
              { Script.Shavian, new[] { Tag.Parse("shaw") } },
              { Script.Sharada, new[] { Tag.Parse("shrd") } },
              { Script.Siddham, new[] { Tag.Parse("sidd") } },
              { Script.Khudawadi, new[] { Tag.Parse("sind") } },
              { Script.Sinhala, new[] { Tag.Parse("sinh") } },
              { Script.Sogdian, new[] { Tag.Parse("sogd") } },
              { Script.OldSogdian, new[] { Tag.Parse("sogo") } },
              { Script.SoraSompeng, new[] { Tag.Parse("sora") } },
              { Script.Soyombo, new[] { Tag.Parse("soyo") } },
              { Script.Sundanese, new[] { Tag.Parse("sund") } },
              { Script.SylotiNagri, new[] { Tag.Parse("sylo") } },
              { Script.Syriac, new[] { Tag.Parse("syrc") } },
              { Script.Tagbanwa, new[] { Tag.Parse("tagb") } },
              { Script.Takri, new[] { Tag.Parse("takr") } },
              { Script.TaiLe, new[] { Tag.Parse("tale") } },
              { Script.NewTaiLue, new[] { Tag.Parse("talu") } },
              { Script.Tamil, new[] { Tag.Parse("taml") } },
              { Script.Tangut, new[] { Tag.Parse("tang") } },
              { Script.TaiViet, new[] { Tag.Parse("tavt") } },
              { Script.Telugu, new[] { Tag.Parse("telu") } },
              { Script.Tifinagh, new[] { Tag.Parse("tfng") } },
              { Script.Tagalog, new[] { Tag.Parse("tglg") } },
              { Script.Thaana, new[] { Tag.Parse("thaa") } },
              { Script.Thai, new[] { Tag.Parse("thai") } },
              { Script.Tibetan, new[] { Tag.Parse("tibt") } },
              { Script.Tirhuta, new[] { Tag.Parse("tirh") } },
              { Script.Ugaritic, new[] { Tag.Parse("ugar") } },
              { Script.Vai, new[] { Tag.Parse("vaii") } },
              { Script.WarangCiti, new[] { Tag.Parse("wara") } },
              { Script.Wancho, new[] { Tag.Parse("wcho") } },
              { Script.OldPersian, new[] { Tag.Parse("xpeo") } },
              { Script.Cuneiform, new[] { Tag.Parse("xsux") } },
              { Script.Yezidi, new[] { Tag.Parse("yezi") } },
              { Script.Yi, new[] { Tag.Parse("yiii") } },
              { Script.ZanabazarSquare, new[] { Tag.Parse("zanb") } },
            };
    }
}
