// Copyright (c) Six Labors.
// Licensed under the Six Labors Split License.

using SixLabors.Fonts.Unicode;

namespace SixLabors.Fonts.Tables.AdvancedTypographic;

/// <summary>
/// Provides a map from Unicode <see cref="ScriptClass"/> to OTF <see cref="Tag"/>.
/// <see href="https://docs.microsoft.com/en-us/typography/opentype/spec/scripttags"/>
/// </summary>
internal sealed class UnicodeScriptTagMap : Dictionary<ScriptClass, Tag[]>
{
    private static readonly Lazy<UnicodeScriptTagMap> Lazy = new(() => CreateMap(), true);

    /// <summary>
    /// Prevents a default instance of the <see cref="UnicodeScriptTagMap"/> class from being created.
    /// </summary>
    private UnicodeScriptTagMap()
    {
    }

    public static UnicodeScriptTagMap Instance => Lazy.Value;

    // TODO: This map will likely require updating to add aliases for old fonts.
    // Use HarfBuzz as a reference.
    private static UnicodeScriptTagMap CreateMap()
        => new()
        {
            { ScriptClass.Unknown, [Tag.Parse("zzzz")] },
            { ScriptClass.Common, [Tag.Parse("zyyy")] },
            { ScriptClass.Inherited, [Tag.Parse("zinh")] },
            { ScriptClass.Adlam, [Tag.Parse("adlm")] },
            { ScriptClass.CaucasianAlbanian, [Tag.Parse("aghb")] },
            { ScriptClass.Ahom, [Tag.Parse("ahom")] },
            { ScriptClass.Arabic, [Tag.Parse("arab")] },
            { ScriptClass.ImperialAramaic, [Tag.Parse("armi")] },
            { ScriptClass.Armenian, [Tag.Parse("armn")] },
            { ScriptClass.Avestan, [Tag.Parse("avst")] },
            { ScriptClass.Balinese, [Tag.Parse("bali")] },
            { ScriptClass.Bamum, [Tag.Parse("bamu")] },
            { ScriptClass.BassaVah, [Tag.Parse("bass")] },
            { ScriptClass.Batak, [Tag.Parse("batk")] },
            { ScriptClass.Bengali, [Tag.Parse("bng2"), Tag.Parse("beng")] },
            { ScriptClass.Bhaiksuki, [Tag.Parse("bhks")] },
            { ScriptClass.Bopomofo, [Tag.Parse("bopo")] },
            { ScriptClass.Brahmi, [Tag.Parse("brah")] },
            { ScriptClass.Braille, [Tag.Parse("brai")] },
            { ScriptClass.Buginese, [Tag.Parse("bugi")] },
            { ScriptClass.Buhid, [Tag.Parse("buhd")] },
            { ScriptClass.Chakma, [Tag.Parse("cakm")] },
            { ScriptClass.CanadianAboriginal, [Tag.Parse("cans")] },
            { ScriptClass.Carian, [Tag.Parse("cari")] },
            { ScriptClass.Cham, [Tag.Parse("cham")] },
            { ScriptClass.Cherokee, [Tag.Parse("cher")] },
            { ScriptClass.Chorasmian, [Tag.Parse("chrs")] },
            { ScriptClass.Coptic, [Tag.Parse("copt")] },
            { ScriptClass.CyproMinoan, [Tag.Parse("cpmn")] },
            { ScriptClass.Cypriot, [Tag.Parse("cprt")] },
            { ScriptClass.Cyrillic, [Tag.Parse("cyrl")] },
            { ScriptClass.Devanagari, [Tag.Parse("dev2"), Tag.Parse("deva")] },
            { ScriptClass.DivesAkuru, [Tag.Parse("diak")] },
            { ScriptClass.Dogra, [Tag.Parse("dogr")] },
            { ScriptClass.Deseret, [Tag.Parse("dsrt")] },
            { ScriptClass.Duployan, [Tag.Parse("dupl")] },
            { ScriptClass.EgyptianHieroglyphs, [Tag.Parse("egyp")] },
            { ScriptClass.Elbasan, [Tag.Parse("elba")] },
            { ScriptClass.Elymaic, [Tag.Parse("elym")] },
            { ScriptClass.Ethiopic, [Tag.Parse("ethi")] },
            { ScriptClass.Georgian, [Tag.Parse("geor")] },
            { ScriptClass.Glagolitic, [Tag.Parse("glag")] },
            { ScriptClass.GunjalaGondi, [Tag.Parse("gong")] },
            { ScriptClass.MasaramGondi, [Tag.Parse("gonm")] },
            { ScriptClass.Gothic, [Tag.Parse("goth")] },
            { ScriptClass.Grantha, [Tag.Parse("gran")] },
            { ScriptClass.Greek, [Tag.Parse("grek")] },
            { ScriptClass.Gujarati, [Tag.Parse("gjr2"), Tag.Parse("gujr")] },
            { ScriptClass.Gurmukhi, [Tag.Parse("gur2"), Tag.Parse("guru")] },
            { ScriptClass.Hangul, [Tag.Parse("hang")] },
            { ScriptClass.Han, [Tag.Parse("hani")] },
            { ScriptClass.Hanunoo, [Tag.Parse("hano")] },
            { ScriptClass.Hatran, [Tag.Parse("hatr")] },
            { ScriptClass.Hebrew, [Tag.Parse("hebr")] },
            { ScriptClass.Hiragana, [Tag.Parse("hira")] },
            { ScriptClass.AnatolianHieroglyphs, [Tag.Parse("hluw")] },
            { ScriptClass.PahawhHmong, [Tag.Parse("hmng")] },
            { ScriptClass.NyiakengPuachueHmong, [Tag.Parse("hmnp")] },
            { ScriptClass.KatakanaOrHiragana, [Tag.Parse("hrkt")] },
            { ScriptClass.OldHungarian, [Tag.Parse("hung")] },
            { ScriptClass.OldItalic, [Tag.Parse("ital")] },
            { ScriptClass.Javanese, [Tag.Parse("java")] },
            { ScriptClass.KayahLi, [Tag.Parse("kali")] },
            { ScriptClass.Katakana, [Tag.Parse("kana")] },
            { ScriptClass.Kharoshthi, [Tag.Parse("khar")] },
            { ScriptClass.Khmer, [Tag.Parse("khmr")] },
            { ScriptClass.Khojki, [Tag.Parse("khoj")] },
            { ScriptClass.KhitanSmallScript, [Tag.Parse("kits")] },
            { ScriptClass.Kannada, [Tag.Parse("knd2"), Tag.Parse("knda")] },
            { ScriptClass.Kaithi, [Tag.Parse("kthi")] },
            { ScriptClass.TaiTham, [Tag.Parse("lana")] },
            { ScriptClass.Lao, [Tag.Parse("laoo")] },
            { ScriptClass.Latin, [Tag.Parse("latn")] },
            { ScriptClass.Lepcha, [Tag.Parse("lepc")] },
            { ScriptClass.Limbu, [Tag.Parse("limb")] },
            { ScriptClass.LinearA, [Tag.Parse("lina")] },
            { ScriptClass.LinearB, [Tag.Parse("linb")] },
            { ScriptClass.Lisu, [Tag.Parse("lisu")] },
            { ScriptClass.Lycian, [Tag.Parse("lyci")] },
            { ScriptClass.Lydian, [Tag.Parse("lydi")] },
            { ScriptClass.Mahajani, [Tag.Parse("mahj")] },
            { ScriptClass.Makasar, [Tag.Parse("maka")] },
            { ScriptClass.Mandaic, [Tag.Parse("mand")] },
            { ScriptClass.Manichaean, [Tag.Parse("mani")] },
            { ScriptClass.Marchen, [Tag.Parse("marc")] },
            { ScriptClass.Medefaidrin, [Tag.Parse("medf")] },
            { ScriptClass.MendeKikakui, [Tag.Parse("mend")] },
            { ScriptClass.MeroiticCursive, [Tag.Parse("merc")] },
            { ScriptClass.MeroiticHieroglyphs, [Tag.Parse("mero")] },
            { ScriptClass.Malayalam, [Tag.Parse("mlm2"), Tag.Parse("mlym")] },
            { ScriptClass.Modi, [Tag.Parse("modi")] },
            { ScriptClass.Mongolian, [Tag.Parse("mong")] },
            { ScriptClass.Mro, [Tag.Parse("mroo")] },
            { ScriptClass.MeeteiMayek, [Tag.Parse("mtei")] },
            { ScriptClass.Multani, [Tag.Parse("mult")] },
            { ScriptClass.Myanmar, [Tag.Parse("mym2"), Tag.Parse("mymr")] },
            { ScriptClass.Nandinagari, [Tag.Parse("nand")] },
            { ScriptClass.OldNorthArabian, [Tag.Parse("narb")] },
            { ScriptClass.Nabataean, [Tag.Parse("nbat")] },
            { ScriptClass.Newa, [Tag.Parse("newa")] },
            { ScriptClass.Nko, [Tag.Parse("nkoo")] },
            { ScriptClass.Nushu, [Tag.Parse("nshu")] },
            { ScriptClass.Ogham, [Tag.Parse("ogam")] },
            { ScriptClass.OlChiki, [Tag.Parse("olck")] },
            { ScriptClass.OldTurkic, [Tag.Parse("orkh")] },
            { ScriptClass.Oriya, [Tag.Parse("ory2"), Tag.Parse("orya")] },
            { ScriptClass.Osage, [Tag.Parse("osge")] },
            { ScriptClass.Osmanya, [Tag.Parse("osma")] },
            { ScriptClass.OldUyghur, [Tag.Parse("ougr")] },
            { ScriptClass.Palmyrene, [Tag.Parse("palm")] },
            { ScriptClass.PauCinHau, [Tag.Parse("pauc")] },
            { ScriptClass.OldPermic, [Tag.Parse("perm")] },
            { ScriptClass.PhagsPa, [Tag.Parse("phag")] },
            { ScriptClass.InscriptionalPahlavi, [Tag.Parse("phli")] },
            { ScriptClass.PsalterPahlavi, [Tag.Parse("phlp")] },
            { ScriptClass.Phoenician, [Tag.Parse("phnx")] },
            { ScriptClass.Miao, [Tag.Parse("plrd")] },
            { ScriptClass.InscriptionalParthian, [Tag.Parse("prti")] },
            { ScriptClass.Rejang, [Tag.Parse("rjng")] },
            { ScriptClass.HanifiRohingya, [Tag.Parse("rohg")] },
            { ScriptClass.Runic, [Tag.Parse("runr")] },
            { ScriptClass.Samaritan, [Tag.Parse("samr")] },
            { ScriptClass.OldSouthArabian, [Tag.Parse("sarb")] },
            { ScriptClass.Saurashtra, [Tag.Parse("saur")] },
            { ScriptClass.SignWriting, [Tag.Parse("sgnw")] },
            { ScriptClass.Shavian, [Tag.Parse("shaw")] },
            { ScriptClass.Sharada, [Tag.Parse("shrd")] },
            { ScriptClass.Siddham, [Tag.Parse("sidd")] },
            { ScriptClass.Khudawadi, [Tag.Parse("sind")] },
            { ScriptClass.Sinhala, [Tag.Parse("sinh")] },
            { ScriptClass.Sogdian, [Tag.Parse("sogd")] },
            { ScriptClass.OldSogdian, [Tag.Parse("sogo")] },
            { ScriptClass.SoraSompeng, [Tag.Parse("sora")] },
            { ScriptClass.Soyombo, [Tag.Parse("soyo")] },
            { ScriptClass.Sundanese, [Tag.Parse("sund")] },
            { ScriptClass.SylotiNagri, [Tag.Parse("sylo")] },
            { ScriptClass.Syriac, [Tag.Parse("syrc")] },
            { ScriptClass.Tagbanwa, [Tag.Parse("tagb")] },
            { ScriptClass.Takri, [Tag.Parse("takr")] },
            { ScriptClass.TaiLe, [Tag.Parse("tale")] },
            { ScriptClass.NewTaiLue, [Tag.Parse("talu")] },
            { ScriptClass.Tamil, [Tag.Parse("tml2"), Tag.Parse("taml")] },
            { ScriptClass.Tangut, [Tag.Parse("tang")] },
            { ScriptClass.TaiViet, [Tag.Parse("tavt")] },
            { ScriptClass.Telugu, [Tag.Parse("tel2"), Tag.Parse("telu")] },
            { ScriptClass.Tifinagh, [Tag.Parse("tfng")] },
            { ScriptClass.Tagalog, [Tag.Parse("tglg")] },
            { ScriptClass.Thaana, [Tag.Parse("thaa")] },
            { ScriptClass.Thai, [Tag.Parse("thai")] },
            { ScriptClass.Tibetan, [Tag.Parse("tibt")] },
            { ScriptClass.Tirhuta, [Tag.Parse("tirh")] },
            { ScriptClass.Tangsa, [Tag.Parse("tnsa")] },
            { ScriptClass.Toto, [Tag.Parse("toto")] },
            { ScriptClass.Ugaritic, [Tag.Parse("ugar")] },
            { ScriptClass.Vai, [Tag.Parse("vaii")] },
            { ScriptClass.Vithkuqi, [Tag.Parse("vith")] },
            { ScriptClass.WarangCiti, [Tag.Parse("wara")] },
            { ScriptClass.Wancho, [Tag.Parse("wcho")] },
            { ScriptClass.OldPersian, [Tag.Parse("xpeo")] },
            { ScriptClass.Cuneiform, [Tag.Parse("xsux")] },
            { ScriptClass.Yezidi, [Tag.Parse("yezi")] },
            { ScriptClass.Yi, [Tag.Parse("yiii")] },
            { ScriptClass.ZanabazarSquare, [Tag.Parse("zanb")] },
        };
}
